"""
URL configuration for assistente_krill_web project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from painel import krill_fase2, krill_telas, tms_expedicao, views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('home/', views.dashboard, name='home'),
    path('gestao/', views.painel_gestao, name='painel_gestao'),
    path('central-servidor/', views.central_servidor, name='central_servidor'),
    path('login/', views.login_view, name='login'),
    path('esqueci-senha/', views.solicitar_senha, name='solicitar_senha'),
    path('solicitar-acesso/', views.solicitar_acesso, name='solicitar_acesso'),
    path('status-versao/', views.app_status, name='app_status'),
    path('manifest.webmanifest', views.pwa_manifest, name='pwa_manifest'),
    path('manifest.json', views.pwa_manifest, name='pwa_manifest_json'),
    path('service-worker.js', views.service_worker, name='service_worker'),
    path('sw.js', views.service_worker, name='service_worker_alias'),
    path('apple-touch-icon.png', views.pwa_icon, {"filename": "apple-touch-icon.png"}, name='apple_touch_icon'),
    path('apple-touch-icon-precomposed.png', views.pwa_icon, {"filename": "apple-touch-icon-precomposed.png"}, name='apple_touch_icon_precomposed'),
    path('favicon.ico', views.pwa_icon, {"filename": "favicon.ico"}, name='favicon'),
    path('push/public-key/', views.push_public_key, name='push_public_key'),
    path('push/status/', views.push_status, name='push_status'),
    path('push/subscribe/', views.push_subscribe, name='push_subscribe'),
    path('push/unsubscribe/', views.push_unsubscribe, name='push_unsubscribe'),
    path('push/teste/', views.push_test, name='push_test'),
    path('notificacoes/lida/', views.notification_read, name='notification_read'),
    path('offline/', views.offline, name='offline'),
    path('health/', views.health_status, name='health'),
    path('status-saude/', views.health_status, name='health_status'),
    path('sentinela/', views.sentinela_servidor, name='sentinela_servidor'),
    path('manter-online/', views.keepalive, name='keepalive'),
    path('frota/', views.frota_hub, name='frota_hub'),
    path('colaboradores/', views.colaboradores_hub, name='colaboradores_hub'),
    path('central/<slug:key>/', views.central_personalizada, name='central_personalizada'),
    path('sair/', views.logout_view, name='logout'),
    path('modo-demonstracao/', views.modo_demonstracao, name='modo_demonstracao'),
    path('trocar-cd/', views.set_cd, name='set_cd'),
    path('modulo/<str:key>/data=<path:legacy_query>', views.module_legacy_query_redirect, name='module_legacy_query_redirect'),
    path('modulo/<str:key>/', views.module_list, name='module_list'),
    path('modulo/<str:key>/<int:pk>/editar/', views.module_edit, name='module_edit'),
    path('modulo/<str:key>/<int:pk>/excluir/', views.module_delete, name='module_delete'),
    path('usuarios/', views.usuarios, name='usuarios'),
    path('minha-tela/', views.preferencias, name='preferencias'),
    path('recursos-sistema/', views.recursos_sistema, name='recursos_sistema'),
    path('apresentacao-sistema/', views.apresentacao_sistema, name='apresentacao_sistema'),
    path('treinamento-sistema/', views.treinamento_sistema, name='treinamento_sistema'),
    path('notificacoes-push/', views.notificacoes_push, name='notificacoes_push'),
    path('personalizar-interface/', views.personalizar_interface, name='personalizar_interface'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('minhas-solicitacoes/', views.minhas_solicitacoes, name='minhas_solicitacoes'),
    path('painel-master/', views.auditoria, name='auditoria'),
    path('diagnostico/', views.diagnostico, name='diagnostico'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('importar/', views.importar, name='importar'),
    path('corrigir-cd/', views.corrigir_cd, name='corrigir_cd'),
    path('tms/expedicao/', tms_expedicao.tms_expedicao_page, name='tms_expedicao'),
    path('api/tms/expedicao', tms_expedicao.tms_expedicao_api, name='api_tms_expedicao'),
    path('inicio', krill_telas.alias_home),
    path('inicio/', krill_telas.alias_home),
    path('dashboard', krill_telas.alias_home),
    path('dashboard/', krill_telas.alias_home),
    path('tms/', krill_telas.tms_dashboard, name='tms_dashboard'),
    path('tms/dashboard/', krill_telas.tms_dashboard),
    path('tms/painel-tv/', krill_telas.tms_painel_tv),
    path('tms/painel-tv', krill_telas.tms_painel_tv),
    path('tms/romaneios/', krill_telas.tms_romaneios, name='tms_romaneios'),
    path('tms/romaneios/novo/', krill_telas.tms_romaneios_novo),
    path('tms/romaneios/exportar/', krill_telas.tms_romaneios_export),
    path('tms/romaneios/rascunhos/', krill_telas.tms_rascunhos),
    path('tms/romaneios/rascunhos/atualizacoes/', krill_telas.tms_rascunhos_feed),
    path('tms/romaneios/<int:pk>/', krill_telas.tms_romaneio_detalhe),
    path('tms/romaneios/<int:pk>/status/', krill_fase2.tms_romaneio_status),
    path('tms/romaneios/<int:pk>/km/', krill_fase2.tms_romaneio_km),
    path('tms/romaneios/<int:pk>/bluesoft/', krill_fase2.tms_romaneio_bluesoft),
    path('tms/romaneios/<int:pk>/devolucao/', krill_fase2.tms_romaneio_devolucao),
    path('tms/romaneios/<int:pk>/excluir/', krill_fase2.tms_romaneio_excluir),
    path('tms/viagens/<int:pk>/', krill_fase2.tms_viagem_detalhe),
    path('tms/mdfe/', krill_fase2.tms_mdfe_tela),
    path('api/romaneios/<int:pk>/bipar', krill_fase2.api_romaneio_bipar),
    path('api/romaneios/<int:pk>/bipar/', krill_fase2.api_romaneio_bipar),
    path('api/tms/romaneios', krill_fase2.api_tms_romaneios),
    path('api/tms/romaneios/por-chave', krill_fase2.api_romaneio_por_chave),
    path('api/mdfe/validar', krill_fase2.api_mdfe_validar),
    path('api/mdfe/manifestos', krill_fase2.api_mdfe_manifestos),
    path('api/mdfe/manifestos/<int:pk>', krill_fase2.api_mdfe_detalhe),
    path('api/tms/viagens/forcar-baixa', krill_fase2.api_forcar_baixa),
    path('api/recebimento/retorno-rota', krill_fase2.api_retorno_rota),
    path('api/recebimento/descarga-calcular', krill_fase2.api_descarga_calcular),
    path('api/rotas/calcular', krill_fase2.api_rotas_calcular),
    path('api/stream/kpis', krill_fase2.api_kpis),
    path('api/notificacoes/inbox', krill_fase2.api_inbox),
    path('api/push', views.push_status),
    path('api/telemetry/ping', krill_fase2.api_telemetry_ping),
    path('api/geofence-trigger', krill_fase2.api_geofence_trigger),
    path('api/logistica/dispositivos', krill_fase2.api_dispositivos),
    path('api/logistica/localizacao', krill_fase2.api_localizacao),
    path('api/logistica/motoristas', krill_fase2.api_motoristas),
    path('api/logistica/checkin', krill_fase2.api_checkin_removido),
    path('api/wms/mapa', krill_fase2.api_wms_mapa),
    path('tms/relatorio/', krill_telas.tms_relatorio),
    path('tms/relatorio/exportar/', krill_telas.tms_relatorio_export),
    path('tms/divergencias/', krill_telas.tms_divergencias, name='tms_divergencias'),
    path('tms/divergencias/<int:pk>/status/', krill_telas.tms_divergencia_status),
    path('tms/acompanhamento/', krill_telas.tms_acompanhamento, name='tms_acompanhamento'),
    path('tms/executar/', krill_telas.tms_executar, name='tms_executar'),
    path('tms/rotas/', krill_telas.tms_rotas, name='tms_rotas'),
    path('tms/rotas/otimizar/', krill_telas.tms_otimizar),
    path('tms/viagens/capacidade/', krill_telas.tms_capacidade, name='tms_capacidade'),
    path('tms/monitoramento/mapa/', krill_telas.tms_mapa),
    path('tms/torre-controle/', krill_telas.tms_torre, name='tms_torre'),
    path('tms/torre-controle', krill_telas.tms_torre),
    path('tms/zero-toque/', krill_telas.tms_zero_toque),
    path('tms/checklist-viagem/', krill_telas.tms_checklist),
    path('tms/motorista/painel/', krill_telas.tms_motorista),
    path('tms/motorista/painel', krill_telas.tms_motorista),
    path('tms/transferencias/', krill_telas.tms_transferencias),
    path('tms/recebimento/', krill_telas.tms_recebimento),
    path('tms/recebimento', krill_telas.tms_recebimento),
    path('tms/viagens/vincular/', krill_telas.tms_vincular),
    path('tms/geofencing/cercas/', krill_telas.tms_cercas),
    path('tms/geofencing/dispositivos/', krill_telas.tms_dispositivos),
    path('tms/logistica-reversa/', krill_telas.tms_reversa),
    path('tms/logistica-reversa', krill_telas.tms_reversa),
    path('tms/notificacoes/', krill_telas.alias_to, {"target": "/notificacoes-push/"}),
    path('api/telemetry/live', krill_telas.api_telemetry_live),
    path('api/viagens/validar-capacidade', krill_telas.api_validar_capacidade),
    path('api/tms/geofences', krill_telas.api_geofences),
    path('api/wms/alocar', krill_telas.api_wms_alocar),
    path('wms/mapa/', krill_telas.wms_mapa, name='wms_mapa'),
    path('wms/mapa', krill_telas.wms_mapa),
    path('yms/', krill_telas.yms_patio, name='yms_patio'),
    path('yms/patio/', krill_telas.yms_patio),
    path('patio-docas/', krill_telas.yms_patio),
    path('dashboard/indicadores/', krill_telas.dashboard_indicadores, name='dashboard_indicadores'),
    path('dashboard/indicadores/exportar/', krill_telas.dashboard_indicadores_export),
    path('dashboard/rupturas/', krill_telas.dashboard_rupturas),
    path('dashboard/rupturas/exportar/', krill_telas.dashboard_rupturas_export),
    path('sem-saldo/', krill_telas.sem_saldo),
    path('sem-saldo/novo/', krill_telas.alias_to, {"target": "/modulo/chamados_saldo/"}),
    path('sem-saldo/mobile/', krill_telas.sem_saldo),
    path('sem-saldo/celular/', krill_telas.sem_saldo),
    path('sem-saldo/buscar-produto/', krill_telas.sem_saldo_busca),
    path('sem-saldo/exportar/', krill_telas.sem_saldo_export),
    path('sem-saldo/<int:pk>/finalizar/', krill_fase2.sem_saldo_finalizar),
    path('sem-saldo/<int:pk>/excluir/', krill_fase2.sem_saldo_excluir),
    path('sem-saldo-avaria/', krill_telas.sem_saldo, {"tipo": "avaria"}),
    path('sem-saldo-avaria/novo/', krill_telas.alias_to, {"target": "/modulo/avarias/"}),
    path('sem-saldo-avaria/mobile/', krill_telas.sem_saldo, {"tipo": "avaria"}),
    path('sem-saldo-avaria/celular/', krill_telas.sem_saldo, {"tipo": "avaria"}),
    path('sem-saldo-avaria/exportar/', krill_telas.sem_saldo_export, {"tipo": "avaria"}),
    path('recebimento-operacional/', krill_telas.recebimento_operacional),
    path('recebimento-operacional/portaria/', krill_telas.recebimento_operacional, {"portaria": True}),
    path('recebimento-operacional/novo/', krill_telas.recebimento_novo),
    path('recebimento-operacional/divergencias/', krill_telas.recebimento_divergencias),
    path('recebimento-operacional/exportar/', krill_telas.recebimento_export),
    path('recebimento-parametros-descarga/', krill_telas.recebimento_descarga),
    path('recebimento-relatorio/', krill_telas.recebimento_relatorio),
    path('recebimento-descarga-relatorio/', krill_telas.recebimento_descarga),
    path('recebimento-whatsapp/', krill_telas.recebimento_whatsapp),
    path('recebimento-produtos/', krill_telas.recebimento_produtos),
    path('recebimento-produtos/novo/', krill_telas.recebimento_produto_novo),
    path('recebimento-produtos/exportar/', krill_telas.recebimento_produtos_csv),
    path('recebimento-produtos/exportar-excel/', krill_telas.recebimento_produtos_csv),
    path('recebimento-produtos/importar-nf/', krill_telas.importar_nf),
    path('recebimento/produtos/pesos/', krill_telas.pesos_produtos),
    path('vale-palete/', krill_telas.vale_palete),
    path('vale-palete/novo/', krill_telas.vale_palete_novo),
    path('vale-palete/conta-corrente/', krill_telas.vale_conta),
    path('paletes-rede/conta-corrente/', krill_telas.vale_conta),
    path('separacao-controle/', krill_telas.separacao_controle),
    path('avaria-controle/', krill_telas.avaria_controle),
    path('expedicao-controle/', krill_telas.expedicao_controle),
    path('produtos-cd/', krill_telas.produtos_cd),
    path('produtos-cd/exportar-excel/', krill_telas.recebimento_produtos_csv),
    path('produtos-cd/importar/', krill_telas.alias_to, {"target": "/importar/"}),
    path('exportar-saldo/', krill_telas.sem_saldo_export),
    path('recebimento-operacional/divergencias/exportar/', krill_telas.recebimento_export),
    path('veiculos-disponibilidade/', krill_telas.veiculos_disponibilidade),
    path('alertas/', krill_telas.alertas),
    path('backup/', krill_telas.backup_tela),
    path('auditoria/', krill_telas.auditoria_tela),
    path('ativos/', krill_telas.ativos),
    path('ativos/coletores/', krill_telas.ativos, {"tipo": "coletores"}),
    path('ativos/coletores-ti/', krill_telas.alias_to, {"target": "/modulo/manutencao_equipamentos/"}),
    path('ativos/computadores/', krill_telas.ativos, {"tipo": "computadores"}),
    path('ativos/empilhadeiras/', krill_telas.ativos, {"tipo": "empilhadeiras"}),
    path('ativos/paleteiras/', krill_telas.ativos, {"tipo": "paleteiras"}),
    path('buscar/', krill_telas.buscar),
    path('qualidade-dados/', krill_telas.qualidade_dados),
    path('hub-produtividade/', krill_telas.hub_produtividade),
    path('produtividade-cd/', krill_telas.hub_produtividade),
    path('produtividade-cd/importar/', krill_telas.alias_to, {"target": "/importar/"}),
    path('frota-patio/', krill_telas.alias_to, {"target": "/frota/"}),
    path('frota/simulador', krill_telas.frota_simulador),
    path('frota/simulador/', krill_telas.frota_simulador),
    path('logistica-reversa/', krill_telas.tms_reversa),
    path('regras-separacao/', krill_telas.alias_to, {"target": "/modulo/separacao/"}),
    path('checklist-empilhadeiras/', krill_telas.alias_to, {"target": "/modulo/checklist_frota/"}),
    path('cadastrar-funcionario/', krill_telas.alias_to, {"target": "/colaboradores/"}),
    path('colaboradores/funcionarios/novo/', krill_telas.alias_to, {"target": "/modulo/pessoas_turno/"}),
    path('configuracoes/', krill_telas.alias_to, {"target": "/minha-tela/"}),
    path('configuracoes/matriz-id', krill_telas.alias_to, {"target": "/usuarios/"}),
    path('configuracoes/page-builder', krill_telas.page_builder),
    path('configuracoes/page-builder/', krill_telas.page_builder),
    path('configuracoes/page-builder/<int:pk>/', krill_fase2.page_builder_item),
    path('configuracoes/page-builder/<int:pk>/visualizar/', krill_fase2.page_builder_visualizar),
    path('builder', krill_telas.page_builder),
    path('builder/', krill_telas.page_builder),
    path('personalizar-sistema', krill_telas.alias_to, {"target": "/personalizar-interface/"}),
    path('treinamento', krill_telas.alias_to, {"target": "/treinamento-sistema/"}),
    path('painel-estacao/', krill_telas.alias_home),
    path('trocar-senha/', krill_telas.alias_to, {"target": "/perfil/"}),
    path('perfil/senha/', krill_telas.alias_to, {"target": "/perfil/"}),
    path('perfil/foto/', krill_telas.alias_to, {"target": "/perfil/"}),
    path('ui/abas/', krill_telas.alias_to, {"target": "/personalizar-interface/"}),
    path('modulo/recebimentos', krill_telas.alias_to, {"target": "/modulo/recebimentos/"}),
    path('modulo/recebimento_agenda', krill_telas.alias_to, {"target": "/modulo/recebimento_agenda/"}),
    path('admin/', admin.site.urls),
]
