from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import painel.models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0008_equipamento_manutencao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistFrota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cd_unidade", models.CharField(choices=[("806", "CD 806 - Japui"), ("801", "CD 801")], default="806", max_length=3, verbose_name="CD")),
                ("data", models.DateField(default=painel.models.today, verbose_name="Data")),
                ("observacao", models.TextField(blank=True, verbose_name="Observacao")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("motorista", models.CharField(max_length=120, verbose_name="Motorista")),
                ("veiculo", models.CharField(max_length=120, verbose_name="Veiculo")),
                ("placa", models.CharField(max_length=20, verbose_name="Placa")),
                ("km_inicial", models.PositiveIntegerField(default=0, verbose_name="KM inicial")),
                ("km_final", models.PositiveIntegerField(default=0, verbose_name="KM final")),
                ("horario_saida", models.TimeField(blank=True, null=True, verbose_name="Horario de saida")),
                ("horario_retorno", models.TimeField(blank=True, null=True, verbose_name="Horario de retorno")),
                ("documentacao_veiculo_ok", models.BooleanField(default=True, verbose_name="Documentacao do veiculo OK")),
                ("documentacao_veiculo_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. documentacao")),
                ("pneus_ok", models.BooleanField(default=True, verbose_name="Pneus OK")),
                ("pneus_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. pneus")),
                ("estepe_ok", models.BooleanField(default=True, verbose_name="Estepe OK")),
                ("estepe_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. estepe")),
                ("macaco_chave_ok", models.BooleanField(default=True, verbose_name="Macaco e chave de roda OK")),
                ("macaco_chave_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. macaco/chave")),
                ("triangulo_ok", models.BooleanField(default=True, verbose_name="Triangulo OK")),
                ("triangulo_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. triangulo")),
                ("extintor_ok", models.BooleanField(default=True, verbose_name="Extintor OK")),
                ("extintor_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. extintor")),
                ("farois_ok", models.BooleanField(default=True, verbose_name="Farois OK")),
                ("farois_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. farois")),
                ("lanternas_ok", models.BooleanField(default=True, verbose_name="Lanternas OK")),
                ("lanternas_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. lanternas")),
                ("luz_freio_ok", models.BooleanField(default=True, verbose_name="Luz de freio OK")),
                ("luz_freio_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. luz de freio")),
                ("setas_ok", models.BooleanField(default=True, verbose_name="Setas OK")),
                ("setas_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. setas")),
                ("luz_re_ok", models.BooleanField(default=True, verbose_name="Luz de re OK")),
                ("luz_re_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. luz de re")),
                ("limpador_para_brisa_ok", models.BooleanField(default=True, verbose_name="Limpador de para-brisa OK")),
                ("limpador_para_brisa_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. limpador")),
                ("agua_limpador_ok", models.BooleanField(default=True, verbose_name="Agua do limpador OK")),
                ("agua_limpador_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. agua do limpador")),
                ("buzina_ok", models.BooleanField(default=True, verbose_name="Buzina OK")),
                ("buzina_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. buzina")),
                ("retrovisores_ok", models.BooleanField(default=True, verbose_name="Retrovisores OK")),
                ("retrovisores_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. retrovisores")),
                ("freios_ok", models.BooleanField(default=True, verbose_name="Freios OK")),
                ("freios_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. freios")),
                ("embreagem_ok", models.BooleanField(default=True, verbose_name="Embreagem OK")),
                ("embreagem_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. embreagem")),
                ("vazamentos_ok", models.BooleanField(default=True, verbose_name="Sem vazamentos aparentes")),
                ("vazamentos_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. vazamentos")),
                ("combustivel_ok", models.BooleanField(default=True, verbose_name="Combustivel OK")),
                ("combustivel_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. combustivel")),
                ("oleo_motor_ok", models.BooleanField(default=True, verbose_name="Oleo do motor OK")),
                ("oleo_motor_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. oleo do motor")),
                ("agua_radiador_ok", models.BooleanField(default=True, verbose_name="Agua do radiador OK")),
                ("agua_radiador_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. agua do radiador")),
                ("cabine_limpa_saida_ok", models.BooleanField(default=True, verbose_name="Cabine limpa na saida")),
                ("cabine_limpa_saida_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. cabine saida")),
                ("bau_limpo_saida_ok", models.BooleanField(default=True, verbose_name="Bau limpo na saida")),
                ("bau_limpo_saida_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. bau saida")),
                ("portas_travas_ok", models.BooleanField(default=True, verbose_name="Portas e travas OK")),
                ("portas_travas_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. portas/travas")),
                ("pane_mecanica", models.BooleanField(default=False, verbose_name="Pane mecanica")),
                ("furo_pneu", models.BooleanField(default=False, verbose_name="Furo de pneu")),
                ("acidente", models.BooleanField(default=False, verbose_name="Acidente")),
                ("multa", models.BooleanField(default=False, verbose_name="Multa")),
                ("avaria_carga", models.BooleanField(default=False, verbose_name="Avaria na carga")),
                ("vazamento_viagem", models.BooleanField(default=False, verbose_name="Vazamento durante viagem")),
                ("outra_ocorrencia", models.BooleanField(default=False, verbose_name="Outra ocorrencia")),
                ("descricao_ocorrencia", models.TextField(blank=True, verbose_name="Descricao da ocorrencia")),
                ("veiculo_limpo_retorno_ok", models.BooleanField(default=True, verbose_name="Veiculo limpo no retorno")),
                ("veiculo_limpo_retorno_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. veiculo retorno")),
                ("bau_limpo_retorno_ok", models.BooleanField(default=True, verbose_name="Bau limpo no retorno")),
                ("bau_limpo_retorno_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. bau retorno")),
                ("combustivel_informado_ok", models.BooleanField(default=True, verbose_name="Combustivel informado")),
                ("combustivel_informado_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. combustivel retorno")),
                ("novas_avarias_ok", models.BooleanField(default=True, verbose_name="Sem novas avarias")),
                ("novas_avarias_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. novas avarias")),
                ("pneus_sem_danos_ok", models.BooleanField(default=True, verbose_name="Pneus sem danos no retorno")),
                ("pneus_sem_danos_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. pneus retorno")),
                ("documentacao_entregue_ok", models.BooleanField(default=True, verbose_name="Documentacao entregue")),
                ("documentacao_entregue_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. documentacao retorno")),
                ("chaves_devolvidas_ok", models.BooleanField(default=True, verbose_name="Chaves devolvidas")),
                ("chaves_devolvidas_obs", models.CharField(blank=True, max_length=180, verbose_name="Obs. chaves")),
                ("necessita_manutencao", models.BooleanField(default=False, verbose_name="Necessita manutencao")),
                ("descricao_manutencao", models.TextField(blank=True, verbose_name="Descricao da manutencao")),
                ("responsavel_frota", models.CharField(blank=True, max_length=120, verbose_name="Responsavel pela frota")),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-data", "-id"]},
        ),
    ]
