# Generated by Codex on 2026-07-02

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


SETORES_INICIAIS = [
    ("recebimento", "Recebimento"),
    ("expedicao", "Expedição"),
    ("conferencia", "Conferência"),
    ("ressuprimento", "Ressuprimento"),
    ("cpd", "CPD"),
    ("limpeza", "Limpeza"),
    ("frota", "Frota"),
    ("motorista", "Motorista"),
]


def criar_funcoes_iniciais(apps, schema_editor):
    FuncaoTurno = apps.get_model("painel", "FuncaoTurno")
    for cd in ["806", "801"]:
        for setor, nome in SETORES_INICIAIS:
            for turno in ["dia", "noite"]:
                FuncaoTurno.objects.get_or_create(
                    cd_unidade=cd,
                    nome=nome,
                    setor=setor,
                    turno=turno,
                    defaults={"ativa": True, "quadro_padrao": 0},
                )


def remover_funcoes_iniciais(apps, schema_editor):
    FuncaoTurno = apps.get_model("painel", "FuncaoTurno")
    FuncaoTurno.objects.filter(nome__in=[nome for _setor, nome in SETORES_INICIAIS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0010_checklistfrota_arla_obs_checklistfrota_arla_ok_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pessoaturno",
            name="setor",
            field=models.CharField(
                choices=[
                    ("recebimento", "Recebimento"),
                    ("expedicao", "Expedição"),
                    ("conferencia", "Conferência"),
                    ("ressuprimento", "Ressuprimento"),
                    ("cpd", "CPD"),
                    ("limpeza", "Limpeza"),
                    ("frota", "Frota"),
                    ("motorista", "Motorista"),
                ],
                default="recebimento",
                max_length=30,
                verbose_name="Setor",
            ),
        ),
        migrations.AddField(
            model_name="pessoaturno",
            name="turno",
            field=models.CharField(
                choices=[("dia", "Dia"), ("noite", "Noite")],
                default="dia",
                max_length=20,
                verbose_name="Turno",
            ),
        ),
        migrations.CreateModel(
            name="FuncaoTurno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cd_unidade", models.CharField(choices=[("806", "CD 806 - Japui"), ("801", "CD 801")], default="806", max_length=3, verbose_name="CD")),
                ("data", models.DateField(default=painel.models.today, verbose_name="Data")),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120, verbose_name="Função")),
                (
                    "setor",
                    models.CharField(
                        choices=[
                            ("recebimento", "Recebimento"),
                            ("expedicao", "Expedição"),
                            ("conferencia", "Conferência"),
                            ("ressuprimento", "Ressuprimento"),
                            ("cpd", "CPD"),
                            ("limpeza", "Limpeza"),
                            ("frota", "Frota"),
                            ("motorista", "Motorista"),
                        ],
                        default="recebimento",
                        max_length=30,
                        verbose_name="Setor",
                    ),
                ),
                ("turno", models.CharField(choices=[("dia", "Dia"), ("noite", "Noite")], default="dia", max_length=20, verbose_name="Turno padrão")),
                ("quadro_padrao", models.PositiveIntegerField(default=0, verbose_name="Quadro padrão")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-data", "-id"],
                "constraints": [
                    models.UniqueConstraint(fields=("cd_unidade", "nome", "setor", "turno"), name="funcao_turno_unica_por_cd")
                ],
            },
        ),
        migrations.RunPython(criar_funcoes_iniciais, remover_funcoes_iniciais),
    ]
