# Generated by Django 6.0.6 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0012_checklistfrota_ocorrencia_rota_loja_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistfrota",
            name="cd_intercalacao",
            field=models.CharField(
                "CD de intercalacao",
                blank=True,
                choices=[("806", "CD 806 - Japui"), ("801", "CD 801")],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="checklistfrota",
            name="intercala_cd",
            field=models.BooleanField("Vai intercalar em outro CD", default=False),
        ),
        migrations.AddField(
            model_name="checklistfrota",
            name="intercalacao_concluida",
            field=models.BooleanField("Intercalacao concluida", default=False),
        ),
        migrations.AddField(
            model_name="checklistfrota",
            name="observacao_intercalacao",
            field=models.TextField("Observacao da intercalacao", blank=True),
        ),
    ]
