# Generated by Django 6.0.6 on 2026-07-02

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0013_checklistfrota_cd_intercalacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialFrota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cd_unidade", models.CharField("CD", choices=[("806", "CD 806 - Japui"), ("801", "CD 801")], default="806", max_length=3)),
                ("data", models.DateField("Data", default=painel.models.today)),
                ("observacao", models.TextField("Observacao", blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("material", models.CharField("Material/peca", max_length=140)),
                ("tipo_material", models.CharField("Tipo", choices=[("peca", "Peca"), ("ferramenta", "Ferramenta"), ("acessorio", "Acessorio"), ("documento", "Documento/kit"), ("outro", "Outro")], default="peca", max_length=20)),
                ("condicao", models.CharField("Condicao", choices=[("boa", "Boa para uso"), ("quebrada", "Quebrada"), ("reparo", "Aguardando reparo"), ("descartada", "Descartada")], default="boa", max_length=20)),
                ("movimento", models.CharField("Movimento", choices=[("entrada", "Entrada"), ("saida", "Saida"), ("inventario", "Inventario"), ("baixa", "Baixa")], default="inventario", max_length=20)),
                ("quantidade", models.PositiveIntegerField("Quantidade", default=1)),
                ("placa", models.CharField("Placa/veiculo", blank=True, max_length=20)),
                ("patrimonio", models.CharField("Patrimonio", blank=True, max_length=80)),
                ("localizacao", models.CharField("Localizacao", blank=True, max_length=120)),
                ("responsavel", models.CharField("Responsavel", blank=True, max_length=120)),
                ("criado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-data", "-id"],
            },
        ),
    ]
