# Generated by Django 6.0.6 on 2026-07-02 23:38

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_materialfrota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='diferenca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='endereco',
            field=models.CharField(blank=True, max_length=80, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='numero_glpi',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número GLPI'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='saldo_fisico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo físico'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='diferenca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Diferença'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='qtd_conferida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qtd. conferida'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='qtd_esperada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qtd. esperada'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='controlepaletevasilhame',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='equipamento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Equipamento/série'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Patrimônio/nome'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em uso'), ('devolvido', 'Devolvido'), ('manutencao', 'Manutenção'), ('perdido', 'Perdido')], default='em_uso', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='equipamentomanutencao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=30, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código da loja'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='materialconsumo',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='materialconsumo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='materialfrota',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='descricao',
            field=models.CharField(max_length=240, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pessoaturno',
            name='ferias',
            field=models.PositiveIntegerField(default=0, verbose_name='Férias'),
        ),
        migrations.AlterField(
            model_name='pessoaturno',
            name='funcao',
            field=models.CharField(max_length=120, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='pessoaturno',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='produtogtin',
            name='endereco',
            field=models.CharField(blank=True, max_length=60, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='produtogtin',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('pix', 'Pix'), ('nao_paga', 'Não paga'), ('acordo_fernanda', 'A/C Fernanda'), ('outro', 'Outro')], max_length=30, verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='recebimentoagenda',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='recebimentoagenda',
            name='periodo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='recebimentoagenda',
            name='tipo_caminhao',
            field=models.CharField(blank=True, max_length=80, verbose_name='Tipo do caminhão'),
        ),
        migrations.AlterField(
            model_name='recebimentoconferente',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='endereco_destino',
            field=models.CharField(blank=True, max_length=80, verbose_name='Endereço destino'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='endereco_origem',
            field=models.CharField(blank=True, max_length=80, verbose_name='Endereço origem'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='categoria',
            field=models.CharField(choices=[('geral', '806 - Mercearia líquida geral'), ('agua', '806 - Mercearia líquida água'), ('refrigerante', '806 - Mercearia líquida refrigerante'), ('cerveja', '806 - Mercearia líquida cerveja')], default='geral', max_length=60, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='unitizador',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='unitizador',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='AprovacaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japui'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('setor', models.CharField(choices=[('recebimento', 'Recebimento'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor')),
                ('titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('solicitante', models.CharField(blank=True, max_length=120, verbose_name='Solicitante')),
                ('nivel_necessario', models.CharField(choices=[('supervisor', 'Supervisor'), ('gerente', 'Gerente')], default='supervisor', max_length=20, verbose_name='Nivel necessario')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('validado', 'Validado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa/decisao')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes_operacionais', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japui'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('frota', 'Frota'), ('avaria', 'Avaria'), ('equipamento', 'Equipamento'), ('glpi', 'GLPI/Saldo'), ('pessoas', 'Pessoas'), ('recebimento', 'Recebimento'), ('separacao', 'Separacao'), ('expedicao', 'Expedicao'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo')),
                ('setor', models.CharField(choices=[('recebimento', 'Recebimento'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor')),
                ('titulo', models.CharField(max_length=160, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('origem', models.CharField(blank=True, max_length=120, verbose_name='Origem')),
                ('referencia', models.CharField(blank=True, max_length=120, verbose_name='Referencia')),
                ('severidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=20, verbose_name='Severidade')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('analise', 'Em analise'), ('resolvido', 'Resolvido'), ('recorrente', 'Recorrente'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Recorrente')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='Responsavel')),
                ('assumido_em', models.DateTimeField(blank=True, null=True, verbose_name='Assumido em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('solucao', models.TextField(blank=True, verbose_name='Solucao')),
                ('assumido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_assumidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FechamentoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japui'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('turno', models.CharField(choices=[('dia', 'Dia'), ('noite', 'Noite')], default='dia', max_length=20, verbose_name='Turno')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='Responsavel')),
                ('recebimento_fechado', models.BooleanField(default=False, verbose_name='Recebimento fechado')),
                ('expedicao_fechada', models.BooleanField(default=False, verbose_name='Expedicao fechada')),
                ('frota_conferida', models.BooleanField(default=False, verbose_name='Frota conferida')),
                ('pessoas_registradas', models.BooleanField(default=False, verbose_name='Pessoas do turno registradas')),
                ('avarias_revisadas', models.BooleanField(default=False, verbose_name='Avarias revisadas')),
                ('pendencias_amanha', models.BooleanField(default=False, verbose_name='Pendencias abertas para amanha')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisao'), ('fechado', 'Fechado'), ('reaberto', 'Reaberto')], default='rascunho', max_length=20, verbose_name='Status')),
                ('resumo_gerencial', models.TextField(blank=True, verbose_name='Resumo gerencial')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_finalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('cd_unidade', 'data', 'turno'), name='fechamento_unico_por_cd_data_turno')],
            },
        ),
    ]
