# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0015_gestao_operacional"),
    ]

    operations = [
        migrations.AddField(
            model_name="separacao",
            name="setor",
            field=models.CharField("Setor", blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="separacao",
            name="onda_gerada",
            field=models.PositiveIntegerField("Onda gerada", default=0),
        ),
        migrations.AddField(
            model_name="separacao",
            name="total_a_produzir",
            field=models.DecimalField("Total a produzir", decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="separacao",
            name="crossdocking_produzido",
            field=models.DecimalField("Crossdocking produzido", decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="separacao",
            name="separacao_pulmao_produzido",
            field=models.DecimalField("Separacao pulmao produzido", decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="separacao",
            name="separacao_picking_produzido",
            field=models.DecimalField("Separacao picking produzido", decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="separacao",
            name="recursos_picking",
            field=models.PositiveIntegerField("Recursos picking", default=0),
        ),
        migrations.AddField(
            model_name="separacao",
            name="horas_picking",
            field=models.DecimalField("Horas picking", decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="separacao",
            name="recursos_pulmao",
            field=models.PositiveIntegerField("Recursos pulmao", default=0),
        ),
        migrations.AddField(
            model_name="separacao",
            name="horas_pulmao",
            field=models.DecimalField("Horas pulmao", decimal_places=2, default=0, max_digits=8),
        ),
    ]
