# Generated by Django 6.0.6 on 2026-07-03 10:59

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


def migrar_categorias_antigas(apps, schema_editor):
    Separacao = apps.get_model("painel", "Separacao")
    mapa = {
        "geral": "806_geral",
        "agua": "806_agua",
        "refrigerante": "806_refrigerante",
        "cerveja": "806_cerveja",
    }
    for antigo, novo in mapa.items():
        Separacao.objects.filter(categoria=antigo).update(categoria=novo)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0016_separacao_produtividade_unificada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='separacao',
            name='categoria',
            field=models.CharField(choices=[('806_geral', '806 - Mercearia liquida geral'), ('806_agua', '806 - Mercearia liquida agua'), ('806_refrigerante', '806 - Mercearia liquida refrigerante'), ('806_cerveja', '806 - Mercearia liquida cerveja'), ('801_geral', '801 - Mercearia liquida geral'), ('801_agua', '801 - Mercearia liquida agua'), ('801_refrigerante', '801 - Mercearia liquida refrigerante'), ('801_cerveja', '801 - Mercearia liquida cerveja'), ('801_outros', '801 - Outros produtos')], default='806_geral', max_length=60, verbose_name='Categoria'),
        ),
        migrations.RunPython(migrar_categorias_antigas, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LacreFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japui'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.CharField(max_length=120, verbose_name='Motorista')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('loja_destino', models.CharField(max_length=120, verbose_name='Loja destino')),
                ('lacre', models.CharField(max_length=80, verbose_name='Lacre com erro')),
                ('cd_lacre', models.CharField(choices=[('801', 'CD 801'), ('806', 'CD 806'), ('ambos', 'CD 801 e CD 806')], default='806', max_length=10, verbose_name='CD do lacre')),
                ('motivo', models.CharField(choices=[('lacre_nao_confere', 'Lacre nao confere'), ('lacre_rompido', 'Lacre rompido'), ('lacre_faltando', 'Lacre faltando'), ('erro_lancamento', 'Erro de lancamento'), ('troca_lacre', 'Troca de lacre'), ('outro', 'Outro')], default='lacre_nao_confere', max_length=30, verbose_name='Motivo do erro')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao da ocorrencia')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_analise', 'Em analise'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('tratado_por', models.CharField(blank=True, max_length=120, verbose_name='Tratado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
    ]
