# Generated by Django 6.0.6 on 2026-07-03 13:33

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


def seed_parametros_cd(apps, schema_editor):
    ParametroCD = apps.get_model("painel", "ParametroCD")
    dados = [
        ("806", "local_estoque", "cd_japui", "CD Japuí", 1),
        ("806", "local_estoque", "avaria_japui", "Avaria Japuí", 2),
        ("801", "area", "1", "1", 1),
        ("801", "area", "2", "2", 2),
        ("801", "local_estoque", "cd", "CD", 1),
        ("801", "local_estoque", "cd_cesta_basica", "CD Cesta Básica", 2),
        ("801", "local_estoque", "cd_separacao", "CD Separação", 3),
        ("801", "local_estoque", "estoque_avaria", "Estoque Avaria", 4),
        ("801", "atividade", "ressuprimento_picking", "Ressuprimento de Picking", 1),
        ("801", "atividade", "separacao_picking", "Separação Picking", 2),
        ("801", "atividade", "separacao_pulmao", "Separação Pulmão", 3),
        ("801", "atividade", "movimentacao_doca_pulmao", "Movimentação da Doca para o Pulmão", 4),
        ("801", "atividade", "enderecamento_picking", "Endereçamento de Picking", 5),
        ("801", "atividade", "carregamento_veiculo", "Carregamento de Veículo", 6),
        ("801", "atividade", "finalizacao_pulmao", "Finalização de Pulmão", 7),
        ("801", "atividade", "conferencia_unitizador", "Conferência de Unitizador", 8),
        ("801", "atividade", "separacao_cross_docking", "Separação Cross Docking", 9),
        ("801", "atividade", "movimentacao_pulmao", "Movimentação de Pulmão", 10),
        ("801", "atividade", "finalizacao_ressuprimento", "Finalização de Ressuprimento", 11),
        ("801", "atividade", "rateamento_carga", "Rateamento de Carga", 12),
        ("801", "atividade", "separacao_blocado", "Separação Blocado", 13),
        ("801", "atividade", "inventario_contagem", "Inventário Contagem", 14),
        ("801", "atividade", "movimentar_para_box", "Movimentar para Box", 15),
        ("801", "atividade", "inventario_recontagem", "Inventário Recontagem", 16),
        ("801", "atividade", "enderecamento_pulmao", "Endereçamento de Pulmão", 17),
        ("801", "atividade", "movimentacao_endereco_logistico", "Movimentação de Endereço Logístico", 18),
        ("801", "atividade", "pedido_separacao_externo_picking", "Pedido de Separação Externo Picking", 19),
        ("801", "atividade", "pedido_separacao_externo_pulmao", "Pedido de Separação Externo Pulmão", 20),
        ("801", "atividade", "movimentacao_entre_locais_picking", "Movimentação Entre Locais de Estoque de Picking", 21),
        ("801", "atividade", "movimentacao_entre_locais_pulmao", "Movimentação Entre Locais de Estoque de Pulmão", 22),
        ("801", "atividade", "conferencia_cross_docking", "Conferência Cross Docking", 23),
    ]
    dados.extend(("801", "rua", str(numero), str(numero), numero) for numero in range(1, 12))
    for cd_unidade, tipo, codigo, nome, ordem in dados:
        ParametroCD.objects.update_or_create(
            cd_unidade=cd_unidade,
            tipo=tipo,
            codigo=codigo,
            defaults={"nome": nome, "ordem": ordem, "ativo": True},
        )


def unseed_parametros_cd(apps, schema_editor):
    ParametroCD = apps.get_model("painel", "ParametroCD")
    ParametroCD.objects.filter(cd_unidade__in=["801", "806"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0017_lacres_frota_categorias_cd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ressuprimentopainel',
            name='area',
            field=models.CharField(blank=True, max_length=80, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='ressuprimentopainel',
            name='atividade',
            field=models.CharField(blank=True, max_length=160, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='ressuprimentopainel',
            name='local_estoque',
            field=models.CharField(blank=True, max_length=120, verbose_name='Local de estoque'),
        ),
        migrations.AlterField(
            model_name='aprovacaooperacional',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='cd_unidade',
            field=models.CharField(blank=True, choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], max_length=3),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='chamadosaldo',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='cd_intercalacao',
            field=models.CharField(blank=True, choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], max_length=3, verbose_name='CD de intercalacao'),
        ),
        migrations.AlterField(
            model_name='checklistfrota',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='controlepaletevasilhame',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='equipamentomanutencao',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='fechamentodia',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='funcaoturno',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='lacrefrota',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='materialconsumo',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='materialfrota',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='melhoriasistema',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaoperacional',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='pendencia',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='perfilacesso',
            name='cd_padrao',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3),
        ),
        migrations.AlterField(
            model_name='pessoaturno',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='produtogtin',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='recebimentoagenda',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='recebimentoconferente',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='ressuprimento',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='pendencia_itens',
            field=models.PositiveIntegerField(default=0, verbose_name='Pendência itens'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='pendencia_volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pendência volume'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='pulmao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Pulmão'),
        ),
        migrations.AlterField(
            model_name='ressuprimentopainel',
            name='tipo_painel',
            field=models.CharField(choices=[('demanda', 'Demanda'), ('ocupacao', 'Ocupação'), ('producao', 'Produção')], default='demanda', max_length=20, verbose_name='Tipo de painel'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='categoria',
            field=models.CharField(choices=[('806_geral', '806 - Mercearia líquida geral'), ('806_agua', '806 - Mercearia líquida água'), ('806_refrigerante', '806 - Mercearia líquida refrigerante'), ('806_cerveja', '806 - Mercearia líquida cerveja'), ('801_geral', '801 - Mercearia líquida geral'), ('801_agua', '801 - Mercearia líquida água'), ('801_refrigerante', '801 - Mercearia líquida refrigerante'), ('801_cerveja', '801 - Mercearia líquida cerveja'), ('801_outros', '801 - Outros produtos')], default='806_geral', max_length=60, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.AlterField(
            model_name='unitizador',
            name='cd_unidade',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD'),
        ),
        migrations.CreateModel(
            name='ParametroCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('area', 'Área'), ('rua', 'Rua'), ('local_estoque', 'Local de estoque'), ('atividade', 'Atividade')], max_length=30, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=80, verbose_name='Código')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cd_unidade', 'tipo', 'ordem', 'nome'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('cd_unidade', 'tipo', 'codigo'), name='parametro_cd_unico')],
            },
        ),
        migrations.RunPython(seed_parametros_cd, unseed_parametros_cd),
    ]
