# Generated by Django 6.0.6 on 2026-07-03 14:00

from django.db import migrations, models


def seed_categorias_separacao(apps, schema_editor):
    ParametroCD = apps.get_model("painel", "ParametroCD")
    Separacao = apps.get_model("painel", "Separacao")
    dados = [
        ("806", "mercearia_liquida_geral", "Mercearia líquida geral", 1),
        ("806", "mercearia_liquida_agua", "Mercearia líquida água", 2),
        ("806", "mercearia_liquida_refrigerante", "Mercearia líquida refrigerante", 3),
        ("806", "mercearia_liquida_cerveja", "Mercearia líquida cerveja", 4),
        ("801", "separacao_picking", "Separação Picking", 1),
        ("801", "separacao_pulmao", "Separação Pulmão", 2),
        ("801", "separacao_cross_docking", "Separação Cross Docking", 3),
        ("801", "separacao_blocado", "Separação Blocado", 4),
        ("801", "pedido_externo_picking", "Pedido de Separação Externo Picking", 5),
        ("801", "pedido_externo_pulmao", "Pedido de Separação Externo Pulmão", 6),
    ]
    for cd_unidade, codigo, nome, ordem in dados:
        ParametroCD.objects.update_or_create(
            cd_unidade=cd_unidade,
            tipo="categoria_separacao",
            codigo=codigo,
            defaults={"nome": nome, "ordem": ordem, "ativo": True},
        )

    setores_801 = [
        ("rua_21_beb_quente_nao_alco", "RUA 21 - Bebida quente e não alcoólica", 1),
        ("rua_99_confinados", "RUA 99 - Confinados", 2),
        ("rua_04_11_seca", "RUA 04/11 - Seca", 3),
        ("rua_05_06_salgada", "RUA 05/06 - Salgada", 4),
        ("rua_01_bazar", "RUA 01 - Bazar", 5),
        ("rua_07_08_09_doce", "RUA 07/08/09 - Doce", 6),
        ("rua_01_tr", "RUA 01 - TR", 7),
        ("rua_02_03_higiene", "RUA 02/03 - Higiene", 8),
        ("rua_01_pet_shop", "RUA 01 - Pet Shop", 9),
        ("rua_06_salgada", "RUA 06 - Salgada", 10),
        ("rua_22_23_24_limpeza", "RUA 22/23/24 - Limpeza", 11),
        ("rua_23_limpeza", "RUA 23 - Limpeza", 12),
        ("rua_24_limpeza", "RUA 24 - Limpeza", 13),
        ("rua_02_higiene", "RUA 02 - Higiene", 14),
        ("rua_03_higiene", "RUA 03 - Higiene", 15),
        ("rua_08_doce", "RUA 08 - Doce", 16),
        ("rua_09_doce", "RUA 09 - Doce", 17),
        ("rua_01_consumo", "RUA 01 - Consumo", 18),
        ("rua_01_insumo", "RUA 01 - Insumo", 19),
        ("rua_22_agua_nao_alcoolicos", "RUA 22 - Água e não alcoólicos", 20),
        ("rua_05_salgada", "RUA 05 - Salgada", 21),
    ]
    for codigo, nome, ordem in setores_801:
        ParametroCD.objects.update_or_create(
            cd_unidade="801",
            tipo="setor_armazenagem",
            codigo=codigo,
            defaults={"nome": nome, "ordem": ordem, "ativo": True},
        )

    mapa_geral = {
        "806_geral": "Mercearia líquida geral",
        "806_agua": "Mercearia líquida água",
        "806_refrigerante": "Mercearia líquida refrigerante",
        "806_cerveja": "Mercearia líquida cerveja",
        "806 - Mercearia líquida geral": "Mercearia líquida geral",
        "806 - Mercearia líquida água": "Mercearia líquida água",
        "806 - Mercearia líquida refrigerante": "Mercearia líquida refrigerante",
        "806 - Mercearia líquida cerveja": "Mercearia líquida cerveja",
        "806 - Mercearia liquida geral": "Mercearia líquida geral",
        "806 - Mercearia liquida agua": "Mercearia líquida água",
        "806 - Mercearia liquida refrigerante": "Mercearia líquida refrigerante",
        "806 - Mercearia liquida cerveja": "Mercearia líquida cerveja",
    }
    mapa_801 = {
        "801_geral": "Separação Picking",
        "801_agua": "Separação Pulmão",
        "801_refrigerante": "Separação Cross Docking",
        "801_cerveja": "Separação Blocado",
        "801_outros": "Pedido de Separação Externo Picking",
        "801 - Mercearia líquida geral": "Separação Picking",
        "801 - Mercearia líquida água": "Separação Pulmão",
        "801 - Mercearia líquida refrigerante": "Separação Cross Docking",
        "801 - Mercearia líquida cerveja": "Separação Blocado",
        "801 - Outros produtos": "Pedido de Separação Externo Picking",
        "801 - Mercearia liquida geral": "Separação Picking",
        "801 - Mercearia liquida agua": "Separação Pulmão",
        "801 - Mercearia liquida refrigerante": "Separação Cross Docking",
        "801 - Mercearia liquida cerveja": "Separação Blocado",
    }
    for antigo, novo in mapa_geral.items():
        Separacao.objects.filter(categoria=antigo).update(categoria=novo)
    for antigo, novo in mapa_801.items():
        Separacao.objects.filter(cd_unidade="801", categoria=antigo).update(categoria=novo)


def unseed_categorias_separacao(apps, schema_editor):
    ParametroCD = apps.get_model("painel", "ParametroCD")
    ParametroCD.objects.filter(tipo__in=["categoria_separacao", "setor_armazenagem"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0018_parametros_cd_backup_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrocd',
            name='tipo',
            field=models.CharField(choices=[('area', 'Área'), ('rua', 'Rua'), ('local_estoque', 'Local de estoque'), ('atividade', 'Atividade'), ('categoria_separacao', 'Categoria da separação'), ('setor_armazenagem', 'Setor de armazenagem')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='horas_pulmao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas pulmão'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='recursos_pulmao',
            field=models.PositiveIntegerField(default=0, verbose_name='Recursos pulmão'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='separacao_picking_produzido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Separação picking produzida'),
        ),
        migrations.AlterField(
            model_name='separacao',
            name='separacao_pulmao_produzido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Separação pulmão produzida'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='horas_pulmao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Horas pulmão'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='recursos_pulmao',
            field=models.PositiveIntegerField(default=0, verbose_name='Recursos pulmão'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='separacao_picking_produzido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Separação picking produzida'),
        ),
        migrations.AlterField(
            model_name='separacaoprodutividade',
            name='separacao_pulmao_produzido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Separação pulmão produzida'),
        ),
        migrations.RunPython(seed_categorias_separacao, unseed_categorias_separacao),
    ]
