# Generated by Django 6.0.6 on 2026-07-06 22:21

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0019_separacao_categorias_por_cd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrota',
            name='itens_personalizados',
            field=models.JSONField(blank=True, default=dict, verbose_name='Itens personalizados'),
        ),
        migrations.CreateModel(
            name='ChecklistFrotaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.CharField(default='Itens adicionais', max_length=120, verbose_name='Grupo')),
                ('titulo', models.CharField(max_length=180, verbose_name='Item do checklist')),
                ('tipo_checklist', models.CharField(choices=[('saida', 'Saída do CD'), ('retorno', 'Retorno ao CD'), ('ambos', 'Saída e retorno')], default='ambos', max_length=12, verbose_name='Tipo de checklist')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'grupo', 'titulo'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.CharField(max_length=120, verbose_name='Colaborador')),
                ('setor', models.CharField(choices=[('recebimento', 'Recebimento'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor')),
                ('funcao', models.CharField(blank=True, max_length=120, verbose_name='Função')),
                ('inicio_ferias', models.DateField(verbose_name='Início das férias')),
                ('fim_ferias', models.DateField(verbose_name='Fim das férias')),
                ('retorno_previsto', models.DateField(verbose_name='Retorno previsto')),
                ('status', models.CharField(choices=[('programada', 'Férias programadas'), ('pre_ferias', 'Próximo das férias'), ('em_ferias', 'Em férias'), ('retornando', 'Retornando'), ('retornado', 'Retornou'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Status')),
                ('notificar_supervisor', models.BooleanField(default=True, verbose_name='Notificar supervisor')),
                ('notificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Notificado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio_ferias', 'colaborador'],
                'abstract': False,
            },
        ),
    ]
