# Generated by Django 6.0.6 on 2026-07-07 09:04

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0020_checklistfrota_itens_personalizados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrotaitem',
            name='campo_sistema',
            field=models.CharField(blank=True, max_length=80, verbose_name='Campo do sistema'),
        ),
        migrations.CreateModel(
            name='ChecklistFrotaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=80, verbose_name='Código interno')),
                ('titulo', models.CharField(max_length=160, verbose_name='Grupo do checklist')),
                ('dica', models.CharField(blank=True, max_length=240, verbose_name='Orientação do grupo')),
                ('tipo_checklist', models.CharField(choices=[('saida', 'Saída do CD'), ('retorno', 'Retorno ao CD'), ('ambos', 'Saída e retorno')], default='ambos', max_length=12, verbose_name='Tipo de checklist')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('mostrar_motorista', models.BooleanField(default=True, verbose_name='Mostrar para motorista')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checklistfrotaitem',
            name='grupo_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='painel.checklistfrotagrupo', verbose_name='Grupo do checklist'),
        ),
        migrations.AddConstraint(
            model_name='checklistfrotagrupo',
            constraint=models.UniqueConstraint(fields=('cd_unidade', 'codigo'), name='checklist_grupo_unico_por_cd'),
        ),
    ]
