# Generated by Django 6.0.6 on 2026-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0021_checklistfrotaitem_campo_sistema_checklistfrotagrupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrota',
            name='loja_destino',
            field=models.CharField(blank=True, max_length=120, verbose_name='Loja destino'),
        ),
    ]
