# Generated by Django 6.0.6 on 2026-07-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0022_checklistfrota_loja_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaosenha',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('respondida', 'Respondida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
