# Generated by Django 6.0.6 on 2026-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0023_alter_solicitacaosenha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaosenha',
            name='lido_pelo_usuario_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
