# Generated by Django 6.0.6 on 2026-07-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0024_solicitacaosenha_lido_pelo_usuario_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='melhoriasistema',
            name='lido_pelo_solicitante_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
