# Generated by Django 6.0.6 on 2026-07-08 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0025_melhoriasistema_lido_pelo_solicitante_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('novo_login', 'Novo login'), ('alterar_acesso', 'Alterar acesso/permissoes'), ('reativar_login', 'Reativar login'), ('outro', 'Outro')], default='novo_login', max_length=30)),
                ('nome', models.CharField(max_length=160)),
                ('login_desejado', models.CharField(blank=True, max_length=150)),
                ('cd_unidade', models.CharField(blank=True, choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], max_length=3)),
                ('cargo', models.CharField(blank=True, max_length=80)),
                ('setor', models.CharField(blank=True, max_length=80)),
                ('contato', models.CharField(blank=True, max_length=120)),
                ('justificativa', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('respondida', 'Respondida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('resposta', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('lido_pelo_usuario_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_acesso_atendidas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
