# Generated by Django 6.0.6 on 2026-07-09 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0031_expedicao_planejamento_remontagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfrota',
            name='acompanhar_retorno',
            field=models.BooleanField(default=False, verbose_name='Acompanhar retorno'),
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='retorno_dispensado',
            field=models.BooleanField(default=False, verbose_name='Retorno dispensado'),
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='retorno_dispensado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno dispensado em'),
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='retorno_dispensado_motivo',
            field=models.CharField(blank=True, max_length=240, verbose_name='Motivo da dispensa do retorno'),
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='retorno_dispensado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_retorno_dispensado', to=settings.AUTH_USER_MODEL, verbose_name='Retorno dispensado por'),
        ),
        migrations.AddField(
            model_name='checklistfrota',
            name='saida_referencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retorno_registrado', to='painel.checklistfrota', verbose_name='Saída de referência'),
        ),
    ]
