# Generated by Django 6.0.6 on 2026-07-10 00:43

import django.db.models.deletion
from django.db import migrations, models


def link_existing_maintenance(apps, schema_editor):
    Equipamento = apps.get_model("painel", "Equipamento")
    Manutencao = apps.get_model("painel", "EquipamentoManutencao")
    equipment_by_key = {}
    for equipment in Equipamento.objects.exclude(patrimonio="").iterator():
        key = (equipment.cd_unidade, "".join(ch for ch in equipment.patrimonio.upper() if ch.isalnum()))
        equipment_by_key.setdefault(key, equipment)
    for maintenance in Manutencao.objects.filter(equipamento_cadastrado__isnull=True).exclude(patrimonio="").iterator():
        key = (maintenance.cd_unidade, "".join(ch for ch in maintenance.patrimonio.upper() if ch.isalnum()))
        equipment = equipment_by_key.get(key)
        if equipment:
            Manutencao.objects.filter(pk=maintenance.pk).update(
                equipamento_cadastrado_id=equipment.pk,
                patrimonio=equipment.patrimonio,
                equipamento=equipment.equipamento,
                tipo=equipment.tipo,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0032_vinculo_saida_retorno_frota'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentomanutencao',
            name='equipamento_cadastrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes', to='painel.equipamento', verbose_name='Equipamento cadastrado'),
        ),
        migrations.RunPython(link_existing_maintenance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aprovacaooperacional',
            name='setor',
            field=models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='colaboradorferias',
            name='setor',
            field=models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='equipamentomanutencao',
            name='patrimonio',
            field=models.CharField(max_length=120, verbose_name='Patrimônio'),
        ),
        migrations.AlterField(
            model_name='funcaoturno',
            name='setor',
            field=models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='ocorrenciaoperacional',
            name='setor',
            field=models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='perfilacesso',
            name='cargo',
            field=models.CharField(choices=[('master', 'Master'), ('gestor_cd', 'Gestor de CD'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('supervisor_recebimento', 'Supervisor de Recebimento'), ('supervisor_separacao', 'Supervisor de Separação'), ('supervisor_conferencia_expedicao', 'Supervisor de Conferência e Expedição'), ('supervisor_frota', 'Supervisor de Frota'), ('lider', 'Líder'), ('lider_separacao', 'Líder de Separação'), ('lider_conferencia_expedicao', 'Líder de Conferência e Expedição'), ('lider_frota', 'Líder de Frota'), ('analista', 'Analista'), ('assistente', 'Assistente'), ('motorista', 'Motorista'), ('consulta', 'Consulta')], default='assistente', max_length=40),
        ),
        migrations.AlterField(
            model_name='pessoaturno',
            name='setor',
            field=models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor'),
        ),
    ]
