# Generated by Django 6.0.6 on 2026-07-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0033_equipamentomanutencao_equipamento_cadastrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='melhoriasistema',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('melhoria', 'Melhoria'), ('implantacao', 'Nova implantação'), ('correcao', 'Correção de problema'), ('outro', 'Outro pedido')], default='melhoria', max_length=20, verbose_name='Tipo de solicitação'),
        ),
    ]
