# Generated by Django 6.0.6 on 2026-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0034_melhoriasistema_tipo_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaturno',
            name='faltas_sem_justificativa',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas sem justificativa'),
        ),
        migrations.AddField(
            model_name='pessoaturno',
            name='folgas',
            field=models.PositiveIntegerField(default=0, verbose_name='Folgas'),
        ),
    ]
