# Generated by Django 6.0.6 on 2026-07-11 10:11

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0038_carregamento_veiculos_permissoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCarregamentoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.CharField(max_length=80, verbose_name='Loja')),
                ('placa', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('motorista', models.CharField(blank=True, max_length=120, verbose_name='Motorista')),
                ('qtd_paletes', models.PositiveIntegerField(default=0, verbose_name='Qtd. paletes')),
                ('periodo', models.CharField(choices=[('manha', 'Manha'), ('tarde', 'Tarde')], default='manha', max_length=30, verbose_name='Periodo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluido')], default='pendente', max_length=20, verbose_name='Status')),
                ('motivo', models.TextField(verbose_name='Motivo da solicitação')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da Frota')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado/recusado em')),
                ('lido_pelo_solicitante_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido pelo solicitante em')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carregamentos_manuais_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expedicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_manuais', to='painel.expedicao')),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
    ]
