# Generated by Django 6.0.6 on 2026-07-11 20:22

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0040_permissoes_aprovacoes_carregamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedicaoFaturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.CharField(max_length=80, verbose_name='Loja')),
                ('placa', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('motorista', models.CharField(blank=True, max_length=120, verbose_name='Motorista')),
                ('qtd_paletes', models.PositiveIntegerField(default=0, verbose_name='Qtd. paletes')),
                ('periodo', models.CharField(choices=[('manha', 'Manha'), ('tarde', 'Tarde')], default='manha', max_length=30, verbose_name='Periodo')),
                ('nota_fiscal', models.CharField(blank=True, max_length=60, verbose_name='Nota fiscal')),
                ('chave_acesso', models.CharField(blank=True, max_length=80, verbose_name='Chave de acesso')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando faturamento'), ('erro_fiscal', 'Erro fiscal'), ('nf_emitida', 'NF emitida'), ('liberado_ronilo', 'Liberado Ronilo/lacre'), ('cancelado', 'Cancelado')], default='aguardando', max_length=30, verbose_name='Status')),
                ('motivo_fiscal', models.TextField(blank=True, verbose_name='Motivo fiscal')),
                ('faturado_em', models.DateTimeField(blank=True, null=True, verbose_name='Faturado em')),
                ('liberado_ronilo_em', models.DateTimeField(blank=True, null=True, verbose_name='Liberado Ronilo/lacre em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamentos', to='painel.expedicaovinculo')),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='SistemaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('url', models.CharField(blank=True, max_length=240)),
                ('categoria', models.CharField(choices=[('geral', 'Geral'), ('frota', 'Frota'), ('expedicao', 'Expedicao'), ('faturamento', 'Faturamento'), ('ferias', 'Ferias')], default='geral', max_length=30)),
                ('cd_unidade', models.CharField(blank=True, choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], max_length=3)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('enviada_push_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
