# Generated by Django 6.0.6 on 2026-07-11

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


DRIVERS = [
    ("allan", "Allan", "STH8D95", True),
    ("anderson", "Anderson", "STR6A35", False),
    ("brendon", "Brendon", "EYA1H33", False),
    ("edilson", "Edilson", "ESP1316", True),
    ("eduardo", "Eduardo", "FXJ7564", False),
    ("godoi", "Godoi", "GAQ4571", True),
    ("jefferson", "Jefferson", "CQU6J55", True),
    ("john.lennon", "John Lennon", "EKJ1380", True),
    ("jose.paulo", "Jose Paulo", "FJD2J56", True),
    ("kenidy", "Kenidy", "FPN1F09", False),
    ("kleber", "Kleber", "", False),
    ("marciel", "Marciel", "EGG7260", False),
    ("muller", "Muller", "FWH8J76", False),
    ("pablo.kalid", "Pablo Kalid", "SUJ6J21", True),
    ("paulo.neto", "Paulo Neto", "FGA3738", False),
    ("paulo.sergio", "Paulo Sergio", "GJR4D46", False),
    ("renato", "Renato", "STY0F57", True),
    ("robervaldo", "Robervaldo", "GEZ1B94", True),
    ("marlusa", "Marlusa", "", False),
]


def create_driver_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    PerfilAcesso = apps.get_model("painel", "PerfilAcesso")
    VeiculoFrota = apps.get_model("painel", "VeiculoFrota")
    password = make_password("123456")

    for username, full_name, placa, plataforma in DRIVERS:
        first_name, _, last_name = full_name.partition(" ")
        user, _created = User.objects.get_or_create(username=username)
        user.first_name = first_name
        user.last_name = last_name
        user.is_active = True
        user.password = password
        user.save(update_fields=["first_name", "last_name", "is_active", "password"])

        PerfilAcesso.objects.update_or_create(
            user=user,
            defaults={
                "cargo": "motorista",
                "cd_padrao": "801",
                "permissoes": ["checklist_frota"],
                "abas_ocultas": [],
            },
        )

        if placa:
            veiculo, _created = VeiculoFrota.objects.get_or_create(
                cd_unidade="801",
                placa=placa,
                motorista=full_name,
                defaults={
                    "tipo_caminhao": "Plataforma" if plataforma else "",
                    "ativo": True,
                    "usuario_motorista": user,
                },
            )
            veiculo.usuario_motorista = user
            if plataforma:
                veiculo.tipo_caminhao = "Plataforma"
            veiculo.ativo = True
            veiculo.save(update_fields=["usuario_motorista", "tipo_caminhao", "ativo", "atualizado_em"])


class Migration(migrations.Migration):
    # PostgreSQL can reject the FK index creation when this schema change and the
    # driver seed run inside one transaction while the table has pending triggers.
    atomic = False

    dependencies = [
        ("painel", "0041_expedicaofaturamento_pushsubscription_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculofrota",
            name="usuario_motorista",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="veiculos_frota",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do motorista",
            ),
        ),
        migrations.RunPython(create_driver_users, migrations.RunPython.noop),
    ]
