# Generated by Django 6.0.6 on 2026-07-12 17:14

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0045_permissao_notificacao_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorferias',
            name='setor_detalhado',
            field=models.CharField(blank=True, max_length=120, verbose_name='Setor/rua detalhada'),
        ),
        migrations.AddField(
            model_name='funcaoturno',
            name='setor_detalhado',
            field=models.CharField(blank=True, max_length=120, verbose_name='Setor/rua detalhada'),
        ),
        migrations.AddField(
            model_name='pessoaturno',
            name='setor_detalhado',
            field=models.CharField(blank=True, max_length=120, verbose_name='Setor/rua detalhada'),
        ),
        migrations.CreateModel(
            name='ColaboradorAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('colaborador', models.CharField(max_length=120, verbose_name='Colaborador')),
                ('setor', models.CharField(choices=[('recebimento', 'Recebimento'), ('separacao', 'Separação'), ('expedicao', 'Expedição'), ('conferencia', 'Conferência'), ('ressuprimento', 'Ressuprimento'), ('operacao_compartilhada', 'Operação compartilhada/Empilhadeira'), ('cpd', 'CPD'), ('limpeza', 'Limpeza'), ('frota', 'Frota'), ('motorista', 'Motorista')], default='recebimento', max_length=30, verbose_name='Setor')),
                ('setor_detalhado', models.CharField(blank=True, max_length=120, verbose_name='Setor/rua detalhada')),
                ('funcao', models.CharField(blank=True, max_length=120, verbose_name='Função')),
                ('tipo', models.CharField(choices=[('atestado', 'Atestado'), ('afastamento', 'Afastamento'), ('falta_sem_justificativa', 'Falta sem justificativa'), ('folga', 'Folga'), ('suspensao', 'Suspensão'), ('outro', 'Outro')], default='atestado', max_length=40, verbose_name='Tipo de ausência')),
                ('inicio', models.DateField(verbose_name='Início')),
                ('fim', models.DateField(verbose_name='Fim')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('programada', 'Programada'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20, verbose_name='Status')),
                ('notificar_supervisor', models.BooleanField(default=True, verbose_name='Notificar supervisor')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio', 'colaborador'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EscalaVeiculoFrota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('motorista_titular', models.CharField(blank=True, max_length=120, verbose_name='Motorista titular')),
                ('motorista_responsavel', models.CharField(max_length=120, verbose_name='Motorista responsável no período')),
                ('inicio', models.DateField(verbose_name='Início da troca')),
                ('fim', models.DateField(verbose_name='Fim da troca')),
                ('motivo', models.CharField(choices=[('ferias', 'Férias'), ('manutencao', 'Manutenção'), ('troca_operacional', 'Troca operacional'), ('apoio', 'Apoio'), ('outro', 'Outro')], default='ferias', max_length=30, verbose_name='Motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_veiculos_frota', to=settings.AUTH_USER_MODEL, verbose_name='Login do responsável')),
            ],
            options={
                'ordering': ['-inicio', 'placa'],
                'abstract': False,
            },
        ),
    ]
