# Generated by Django 6.0.6 on 2026-07-13 12:14

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0047_permissoes_ausencias_escala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCaminhaoCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_necessidade', models.DateField(verbose_name='Data de necessidade')),
                ('qtd_caminhoes', models.PositiveIntegerField(default=1, verbose_name='Qtd. caminhões')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('dia_todo', 'Dia todo')], default='manha', max_length=20, verbose_name='Período')),
                ('motivo', models.CharField(blank=True, max_length=240, verbose_name='Motivo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('atendida', 'Atendida'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da Frota')),
                ('atendido_em', models.DateTimeField(blank=True, null=True, verbose_name='Atendido em')),
                ('lido_pelo_solicitante_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido pelo solicitante em')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_caminhao_atendidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
    ]
