# Generated by Django 6.0.6 on 2026-07-14 13:11

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0049_consolida_saldo_paletes_duplicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCargaPronta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.CharField(max_length=80, verbose_name='Loja')),
                ('qtd_paletes', models.PositiveIntegerField(default=0, verbose_name='Qtd. paletes')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=20, verbose_name='Período')),
                ('status', models.CharField(choices=[('pronta', 'Pronta para carregar'), ('em_carregamento', 'Em carregamento'), ('carregada', 'Carregada'), ('cancelada', 'Cancelada')], default='pronta', max_length=30, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta da Frota')),
                ('tratado_em', models.DateTimeField(blank=True, null=True, verbose_name='Tratado em')),
                ('lido_pelo_solicitante_em', models.DateTimeField(blank=True, null=True, verbose_name='Lido pelo solicitante em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tratado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_prontas_tratadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
    ]
