# Generated by Django 6.0.6 on 2026-07-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0051_permissoes_carga_pronta'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedicaofaturamento',
            name='valor_carga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da carga'),
        ),
        migrations.AddField(
            model_name='solicitacaocarregamentomanual',
            name='valor_carga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor da carga'),
        ),
        migrations.AlterField(
            model_name='expedicao',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=30, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='expedicaovinculo',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], default='manha', max_length=30, verbose_name='Período'),
        ),
    ]
