# Generated by Django 6.0.6 on 2026-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0052_piloto_saldo_global_limpeza'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocaminhaocd',
            name='motoristas_enviados',
            field=models.TextField(blank=True, verbose_name='Motoristas enviados'),
        ),
        migrations.AddField(
            model_name='solicitacaocaminhaocd',
            name='precisa_plataforma',
            field=models.BooleanField(default=False, verbose_name='Precisa de plataforma'),
        ),
        migrations.AddField(
            model_name='solicitacaocaminhaocd',
            name='qtd_plataforma',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtd. plataforma'),
        ),
    ]
