# Generated by Django 6.0.6 on 2026-07-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0053_solicitacaocaminhaocd_motoristas_enviados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacesso',
            name='cd_padrao',
            field=models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801'), ('801+806', 'CD 801 + CD 806')], default='806', max_length=7),
        ),
    ]
