# Generated by Django 6.0.6 on 2026-07-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0054_alter_perfilacesso_cd_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='cd_unidade',
            field=models.CharField(blank=True, choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801'), ('801+806', 'CD 801 + CD 806')], max_length=7),
        ),
    ]
