# Generated by Django 6.0.6 on 2026-07-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0055_auditlog_cd_unificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedicaovinculo',
            name='exige_plataforma',
            field=models.BooleanField(default=False, verbose_name='Exige plataforma'),
        ),
        migrations.AddField(
            model_name='expedicaovinculo',
            name='motivo_plataforma',
            field=models.CharField(blank=True, max_length=160, verbose_name='Motivo plataforma'),
        ),
        migrations.AddField(
            model_name='loja',
            name='loja_plataforma',
            field=models.BooleanField(default=False, verbose_name='Loja plataforma'),
        ),
        migrations.AddField(
            model_name='solicitacaocarregamentomanual',
            name='exige_plataforma',
            field=models.BooleanField(default=False, verbose_name='Exige plataforma'),
        ),
        migrations.AddField(
            model_name='solicitacaocarregamentomanual',
            name='motivo_plataforma',
            field=models.CharField(blank=True, max_length=160, verbose_name='Motivo plataforma'),
        ),
    ]
