# Generated by Django 6.0.6 on 2026-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0058_checklistfrota_tempos_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistfrota',
            name='tipo_checklist',
            field=models.CharField(choices=[('saida', 'Saída do CD'), ('chegada_loja', 'Chegada na loja'), ('saida_loja', 'Saída da loja'), ('retorno', 'Retorno ao CD')], default='saida', max_length=12, verbose_name='Tipo de checklist'),
        ),
        migrations.AlterField(
            model_name='checklistfrotagrupo',
            name='tipo_checklist',
            field=models.CharField(choices=[('saida', 'Saída do CD'), ('chegada_loja', 'Chegada na loja'), ('saida_loja', 'Saída da loja'), ('retorno', 'Retorno ao CD'), ('ambos', 'Todas as etapas')], default='ambos', max_length=12, verbose_name='Tipo de checklist'),
        ),
        migrations.AlterField(
            model_name='checklistfrotaitem',
            name='tipo_checklist',
            field=models.CharField(choices=[('saida', 'Saída do CD'), ('chegada_loja', 'Chegada na loja'), ('saida_loja', 'Saída da loja'), ('retorno', 'Retorno ao CD'), ('ambos', 'Todas as etapas')], default='ambos', max_length=12, verbose_name='Tipo de checklist'),
        ),
    ]
