# Generated by Django 6.0.6 on 2026-07-17 01:50

import django.db.models.deletion
import painel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0059_checklist_loja_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaleteRedeMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('operacao', models.CharField(choices=[('reserva', 'Reserva'), ('transferencia', 'Transferência'), ('retirada', 'Retirada/entrega'), ('ajuste', 'Ajuste')], default='reserva', max_length=20, verbose_name='Operação')),
                ('tipo_palete', models.CharField(choices=[('pbr', 'PBR'), ('chep', 'CHEP'), ('descartavel', 'Descartável'), ('pbr2', 'PBR 2')], default='pbr', max_length=20, verbose_name='Tipo de pallet')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('origem_resumo', models.CharField(blank=True, max_length=240, verbose_name='Origem')),
                ('destino_tipo', models.CharField(choices=[('cd', 'CD'), ('loja', 'Loja'), ('outro', 'Outro local')], default='outro', max_length=20, verbose_name='Tipo de destino')),
                ('destino_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código destino')),
                ('destino_nome', models.CharField(blank=True, max_length=140, verbose_name='Destino')),
                ('solicitante', models.CharField(blank=True, max_length=120, verbose_name='Solicitante')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='concluido', max_length=20, verbose_name='Status')),
                ('fontes', models.JSONField(blank=True, default=list, verbose_name='Fontes')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaleteRedeSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_unidade', models.CharField(choices=[('806', 'CD 806 - Japuí'), ('801', 'CD 801')], default='806', max_length=3, verbose_name='CD')),
                ('data', models.DateField(default=painel.models.today, verbose_name='Data')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('local_tipo', models.CharField(choices=[('cd', 'CD'), ('loja', 'Loja'), ('outro', 'Outro local')], default='cd', max_length=20, verbose_name='Tipo de local')),
                ('local_codigo', models.CharField(blank=True, max_length=20, verbose_name='Código do local')),
                ('local_nome', models.CharField(max_length=140, verbose_name='Local')),
                ('tipo_palete', models.CharField(choices=[('pbr', 'PBR'), ('chep', 'CHEP'), ('descartavel', 'Descartável'), ('pbr2', 'PBR 2')], default='pbr', max_length=20, verbose_name='Tipo de pallet')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Saldo total')),
                ('quebrados', models.PositiveIntegerField(default=0, verbose_name='Quebrados')),
                ('reservados', models.PositiveIntegerField(default=0, verbose_name='Reservados')),
                ('responsavel', models.CharField(blank=True, max_length=120, verbose_name='Responsável')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('local_tipo', 'local_codigo', 'local_nome', 'tipo_palete'), name='palete_rede_saldo_unico')],
            },
        ),
    ]
