# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0060_paletes_rede"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculofrota",
            name="status_operacional",
            field=models.CharField(
                choices=[
                    ("disponivel", "Disponivel"),
                    ("em_rota", "Em rota"),
                    ("ocupado", "Ocupado"),
                    ("manutencao", "Manutencao"),
                    ("limpeza", "Limpeza"),
                    ("indisponivel", "Indisponivel"),
                ],
                default="disponivel",
                max_length=20,
                verbose_name="Status operacional",
            ),
        ),
        migrations.AddField(
            model_name="veiculofrota",
            name="local_atual",
            field=models.CharField(blank=True, max_length=120, verbose_name="Local atual"),
        ),
        migrations.AddField(
            model_name="veiculofrota",
            name="orientacao_frota",
            field=models.TextField(blank=True, verbose_name="Orientacao da frota"),
        ),
        migrations.AddField(
            model_name="checklistfrota",
            name="carga_retorno",
            field=models.BooleanField(default=False, verbose_name="Saiu da loja com carga/transferencia"),
        ),
        migrations.AddField(
            model_name="checklistfrota",
            name="carga_retorno_descricao",
            field=models.TextField(blank=True, verbose_name="O que esta trazendo no caminhao"),
        ),
    ]
