# Generated by Codex on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0061_frota_disponibilidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistfrotaitem",
            name="frequencia",
            field=models.CharField(
                choices=[
                    ("sempre", "Todo checklist"),
                    ("diario", "Diario"),
                    ("semanal", "Semanal"),
                    ("mensal", "Mensal"),
                ],
                default="sempre",
                max_length=20,
                verbose_name="Frequencia",
            ),
        ),
        migrations.AddField(
            model_name="veiculofrota",
            name="tacografo_frequencia",
            field=models.CharField(
                choices=[("diario", "Diario"), ("semanal", "Semanal")],
                default="diario",
                max_length=20,
                verbose_name="Frequencia do tacografo",
            ),
        ),
    ]
