# Generated by Django 6.0.6 on 2026-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0062_checklist_frequencia_tacografo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedicaofaturamento',
            name='carga_bluesoft',
            field=models.CharField(blank=True, max_length=60, verbose_name='Carga BlueSoft'),
        ),
    ]
