# Generated by Django 6.0.6 on 2026-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0063_expedicaofaturamento_carga_bluesoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='empilhadeira_indisponivel',
            field=models.BooleanField(default=False, verbose_name='Empilhadeira indisponivel'),
        ),
    ]
