# Generated by Django 6.0.6 on 2026-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0068_saneia_vinculos_loja_pronta'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedicaovinculo',
            name='ordem_entrega',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem sugerida de entrega'),
        ),
        migrations.AddField(
            model_name='expedicaovinculo',
            name='orientacao_frota',
            field=models.TextField(blank=True, verbose_name='Orientacao da Frota'),
        ),
    ]
