# Generated by Django 6.0.6 on 2026-07-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0069_expedicaovinculo_ordem_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paleteredemovimentacao',
            name='tipo_palete',
            field=models.CharField(choices=[('pbr', 'PBR'), ('pbr2', 'PBR 2'), ('chep', 'CHEP'), ('descartavel', 'Descartável')], default='pbr', max_length=20, verbose_name='Tipo de pallet'),
        ),
        migrations.AlterField(
            model_name='paleteredesaldo',
            name='tipo_palete',
            field=models.CharField(choices=[('pbr', 'PBR'), ('pbr2', 'PBR 2'), ('chep', 'CHEP'), ('descartavel', 'Descartável')], default='pbr', max_length=20, verbose_name='Tipo de pallet'),
        ),
    ]
