# Generated by Django 6.0.6 on 2026-09-30 16:39

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_central_expedicao(apps, schema_editor):
    """Três viagens que exercitam a validação traduzida do Worker: ok, warning, danger."""
    Veiculo = apps.get_model("painel", "TmsVeiculo")
    Viagem = apps.get_model("painel", "TmsViagem")
    Parada = apps.get_model("painel", "TmsViagemParada")
    Evento = apps.get_model("painel", "TmsGeofenceEvento")
    if Viagem.objects.filter(loja_codigo="LJ-EX-OK").exists():
        return
    ok_v = Veiculo.objects.create(id="veh_ok", placa="ABC1D23", capacidade_max_kg=12000, capacidade_max_pallets=28, capacidade_max_m3=40, ativo=True)
    warn_v = Veiculo.objects.create(id="veh_warn", placa="DEF4E56", capacidade_max_kg=8000, capacidade_max_pallets=18, capacidade_max_m3=22, ativo=True)
    bad_v = Veiculo.objects.create(id="veh_bad", placa="GHI7J89", capacidade_max_kg=5000, capacidade_max_pallets=10, capacidade_max_m3=12, ativo=True)
    now = timezone.now()
    ready = Viagem.objects.create(
        motorista_nome="Carlos Souza", veiculo_id=ok_v.placa, loja_codigo="LJ-EX-OK", loja_nome="Krill Centro",
        origem_cd="806", cd_atual="806", status="em_rota", status_logistico="em_transito",
        peso_total_kg=6400, volume_total_m3=18,
    )
    waiting = Viagem.objects.create(
        motorista_nome="Ana Lima", veiculo_id=warn_v.id, loja_codigo="LJ-EX-WAIT", loja_nome="Krill Litoral",
        origem_cd="806", cd_atual="806", status="atribuida", status_logistico="em_patio",
        peso_total_kg=0, volume_total_m3=0,
    )
    blocked = Viagem.objects.create(
        motorista_nome="Paulo Nunes", veiculo_id=bad_v.placa, loja_codigo="LJ-EX-BLOCK", loja_nome="Krill Praia",
        origem_cd="806", cd_atual="806", status="atribuida", status_logistico="em_patio",
        peso_total_kg=9000, volume_total_m3=20,
    )
    Parada.objects.create(id="stop-ok-1", viagem=ready, ordem=1, romaneio_id=1001, paletes=12, status="pendente")
    Parada.objects.create(id="stop-wait-1", viagem=waiting, ordem=1, romaneio_id=1002, paletes=0, status="pendente")
    Parada.objects.create(id="stop-bad-1", viagem=blocked, ordem=1, romaneio_id=1003, paletes=16, status="pendente")
    Evento.objects.create(viagem=ready, geofence_tipo="CD", loja_codigo="", acao="exit", ocorreu_em=now)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0070_alter_paleteredemovimentacao_tipo_palete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmsVeiculo',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('capacidade_max_kg', models.FloatField(default=0)),
                ('capacidade_max_pallets', models.PositiveIntegerField(default=0)),
                ('capacidade_max_m3', models.FloatField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tms_veiculos',
            },
        ),
        migrations.CreateModel(
            name='TmsViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista_nome', models.CharField(blank=True, default='', max_length=160)),
                ('veiculo_id', models.CharField(blank=True, default='', max_length=80)),
                ('loja_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('loja_nome', models.CharField(blank=True, default='', max_length=160)),
                ('origem_cd', models.CharField(blank=True, default='', max_length=7)),
                ('cd_atual', models.CharField(blank=True, default='', max_length=7)),
                ('status', models.CharField(default='atribuida', max_length=30)),
                ('status_logistico', models.CharField(choices=[('em_patio', 'Em pátio'), ('em_transito', 'Em trânsito'), ('em_descarregamento', 'Em descarregamento'), ('em_transito_retorno', 'Em trânsito de retorno'), ('retornou_base', 'Retornou à base')], default='em_patio', max_length=40)),
                ('peso_total_kg', models.FloatField(default=0)),
                ('volume_total_m3', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_viagens',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TmsGeofenceEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geofence_tipo', models.CharField(default='LOJA', max_length=20)),
                ('loja_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('acao', models.CharField(max_length=10)),
                ('ocorreu_em', models.DateTimeField()),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_geofence', to='painel.tmsviagem')),
            ],
            options={
                'db_table': 'logistica_geofence_eventos',
                'ordering': ['-ocorreu_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TmsViagemParada',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('romaneio_id', models.IntegerField(blank=True, null=True)),
                ('paletes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pendente', max_length=40)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='painel.tmsviagem')),
            ],
            options={
                'db_table': 'tms_viagem_paradas',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.RunPython(seed_central_expedicao, migrations.RunPython.noop),
    ]
