# Generated by Django 6.0.6 on 2026-09-30 17:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_krill_telas(apps, schema_editor):
    """Dados mínimos para as telas traduzidas do Worker abrirem com motor real."""
    Romaneio = apps.get_model("painel", "TmsRomaneio")
    if Romaneio.objects.filter(numero_romaneio="ROM-806-001").exists():
        return
    Divergencia = apps.get_model("painel", "TmsDivergencia")
    Devolucao = apps.get_model("painel", "TmsDevolucao")
    Rota = apps.get_model("painel", "TmsRota")
    Cerca = apps.get_model("painel", "TmsGeofence")
    Produto = apps.get_model("painel", "TmsProdutoCapacidade")
    Posicao = apps.get_model("painel", "WmsPosicao")
    Doca = apps.get_model("painel", "YmsDoca")
    Movimento = apps.get_model("painel", "YmsMovimentacao")
    Viagem = apps.get_model("painel", "TmsViagem")
    Telemetria = apps.get_model("painel", "TmsTelemetria")
    hoje = timezone.localdate()
    agora = timezone.now()
    centro = Romaneio.objects.create(
        numero_romaneio="ROM-806-001", data=hoje, hora="08:10", cd_origem="806", loja_destino="LJ-EX-OK Krill Centro",
        motorista="Carlos Souza", placa="ABC1D23", quantidade_nfes=4, valor_total_carga=18200, total_paletes=12,
        paletes_pbr=12, status="em_transporte", km_saida=12000, data_saida=agora, lacres="L-100",
    )
    rascunho = Romaneio.objects.create(
        numero_romaneio="ROM-806-002", data=hoje, hora="09:40", cd_origem="806", loja_destino="LJ-EX-WAIT Krill Litoral",
        motorista="Ana Lima", placa="DEF4E56", total_paletes=0, status="rascunho",
    )
    Romaneio.objects.create(
        numero_romaneio="ROM-806-003", data=hoje, hora="07:15", cd_origem="806", loja_destino="LJ-EX-BLOCK Krill Praia",
        motorista="Paulo Nunes", placa="GHI7J89", total_paletes=16, valor_total_carga=9400, status="conferido",
    )
    Divergencia.objects.create(romaneio=centro, data=hoje, tipo="atraso", severidade="atencao", descricao="Loja aguardando a doca.", responsavel="torre", status="aberta")
    Devolucao.objects.create(romaneio=rascunho, data=hoje, tipo="parcial", motivo="Sobra de fardo", valor_devolvido=120, status="aberta")
    Rota.objects.create(cd_origem="806", loja_codigo="LJ-EX-OK", loja_nome="Krill Centro", distancia_km=12.4, tempo_previsto_minutos=28, ativa=True)
    Rota.objects.create(cd_origem="806", loja_codigo="LJ-EX-WAIT", loja_nome="Krill Litoral", distancia_km=18.1, tempo_previsto_minutos=35, ativa=True)
    Rota.objects.create(cd_origem="806", loja_codigo="LJ-EX-BLOCK", loja_nome="Krill Praia", distancia_km=22.6, tempo_previsto_minutos=41, ativa=True)
    Cerca.objects.create(id="geo_cd_806", nome="CD 806", tipo="CD", latitude=-24.0089, longitude=-46.4128, raio_metros=400, ativo=True)
    Cerca.objects.create(id="geo_loja_centro", nome="Krill Centro", tipo="LOJA", latitude=-23.9789, longitude=-46.3562, raio_metros=180, ativo=True)
    Cerca.objects.create(id="geo_loja_litoral", nome="Krill Litoral", tipo="LOJA", latitude=-24.0142, longitude=-46.4215, raio_metros=180, ativo=True)
    Produto.objects.create(ean="7891000100103", descricao="Arroz tipo 1 5kg", peso_kg_fardo=12, volume_m3_fardo=0.018, paletes_por_fardo=0.05)
    Produto.objects.create(ean="7891000100202", descricao="Feijão carioca 1kg", peso_kg_fardo=10, volume_m3_fardo=0.016, paletes_por_fardo=0.05)
    for rua, nivel, codigo, status, ean, nome, paletes in (
        ("A", 1, "A-01", "OCUPADO", "7891000100103", "Arroz tipo 1 5kg", 4),
        ("A", 1, "A-02", "LIVRE", "", "", 0),
        ("A", 2, "A-03", "BLOQUEADO", "", "", 0),
        ("B", 1, "B-01", "LIVRE", "", "", 0),
        ("B", 1, "B-02", "OCUPADO", "7891000100202", "Feijão carioca 1kg", 2),
    ):
        Posicao.objects.create(cd_codigo="806", rua=rua, nivel=nivel, codigo=codigo, status=status, produto_ean=ean, produto_nome=nome, quantidade_paletes=paletes)
    Doca.objects.create(cd_codigo="806", codigo="D01", nome="Doca 1", status="livre", ativa=True)
    Doca.objects.create(cd_codigo="806", codigo="D02", nome="Doca 2", status="livre", ativa=True)
    Doca.objects.create(cd_codigo="806", codigo="D03", nome="Doca 3", status="descarregando", ativa=True)
    Movimento.objects.create(cd_codigo="806", placa="JKL1A23", transportadora="Krill Log", motorista="Rita Souza", nota_fiscal="NF-90", tipo_operacao="descarregamento", status="aguardando_doca", chegada_em=agora)
    viagem = Viagem.objects.filter(loja_codigo="LJ-EX-OK").first()
    if viagem:
        Telemetria.objects.create(viagem=viagem, placa="ABC1D23", latitude=-23.9918, longitude=-46.3806, ocorreu_em=agora)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0071_tms_central_expedicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBuilderTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('fonte', models.CharField(max_length=60)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'page_builder_telas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TmsGeofence',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(default='LOJA', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('raio_metros', models.PositiveIntegerField(default=300)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_geofences',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TmsProdutoCapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=14, unique=True)),
                ('descricao', models.CharField(max_length=180)),
                ('peso_kg_fardo', models.FloatField(default=0)),
                ('volume_m3_fardo', models.FloatField(default=0)),
                ('paletes_por_fardo', models.FloatField(default=0.05)),
            ],
            options={
                'db_table': 'tms_produto_capacidade',
            },
        ),
        migrations.CreateModel(
            name='TmsRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_romaneio', models.CharField(max_length=40, unique=True)),
                ('data', models.DateField()),
                ('hora', models.CharField(blank=True, default='', max_length=8)),
                ('cd_origem', models.CharField(default='806', max_length=7)),
                ('loja_destino', models.CharField(blank=True, default='', max_length=160)),
                ('endereco_loja', models.CharField(blank=True, default='', max_length=240)),
                ('motorista', models.CharField(blank=True, default='', max_length=160)),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_veiculo', models.CharField(blank=True, default='', max_length=80)),
                ('celular_motorista', models.CharField(blank=True, default='', max_length=30)),
                ('quantidade_nfes', models.PositiveIntegerField(default=0)),
                ('valor_total_carga', models.FloatField(default=0)),
                ('paletes_pbr', models.PositiveIntegerField(default=0)),
                ('paletes_chep', models.PositiveIntegerField(default=0)),
                ('paletes_descartavel', models.PositiveIntegerField(default=0)),
                ('total_paletes', models.PositiveIntegerField(default=0)),
                ('responsavel', models.CharField(blank=True, default='', max_length=160)),
                ('lacres', models.CharField(blank=True, default='', max_length=240)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='rascunho', max_length=40)),
                ('km_saida', models.FloatField(default=0)),
                ('km_chegada', models.FloatField(default=0)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('data_chegada_loja', models.DateTimeField(blank=True, null=True)),
                ('data_retorno_cd', models.DateTimeField(blank=True, null=True)),
                ('recebido_por', models.CharField(blank=True, default='', max_length=160)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('atualizado_por', models.CharField(blank=True, default='', max_length=160)),
                ('ordem_entrega', models.PositiveIntegerField(default=0)),
                ('distancia_rota_km', models.FloatField(default=0)),
                ('tempo_rota_minutos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tms_romaneios',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TmsRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_origem', models.CharField(default='806', max_length=7)),
                ('loja_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('loja_nome', models.CharField(blank=True, default='', max_length=160)),
                ('endereco', models.CharField(blank=True, default='', max_length=240)),
                ('cep_origem', models.CharField(blank=True, default='', max_length=12)),
                ('cep_destino', models.CharField(blank=True, default='', max_length=12)),
                ('distancia_km', models.FloatField(default=0)),
                ('tempo_previsto_minutos', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_rotas',
                'ordering': ['cd_origem', 'loja_nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WmsPosicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_codigo', models.CharField(default='806', max_length=7)),
                ('rua', models.CharField(max_length=10)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('codigo', models.CharField(max_length=20)),
                ('status', models.CharField(default='LIVRE', max_length=20)),
                ('produto_ean', models.CharField(blank=True, default='', max_length=20)),
                ('produto_nome', models.CharField(blank=True, default='', max_length=180)),
                ('quantidade_paletes', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'wms_posicoes',
                'ordering': ['rua', 'nivel', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='YmsDoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_codigo', models.CharField(default='806', max_length=7)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(default='livre', max_length=40)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'yms_docas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TmsDivergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(default='operacional', max_length=30)),
                ('severidade', models.CharField(default='normal', max_length=20)),
                ('descricao', models.TextField(blank=True, default='')),
                ('responsavel', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(default='aberta', max_length=20)),
                ('solucao', models.TextField(blank=True, default='')),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('atualizado_por', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('romaneio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_divergencias',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TmsDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(default='parcial', max_length=30)),
                ('motivo', models.CharField(blank=True, default='', max_length=240)),
                ('quantidade_nfes', models.PositiveIntegerField(default=0)),
                ('valor_devolvido', models.FloatField(default=0)),
                ('paletes_pbr', models.PositiveIntegerField(default=0)),
                ('paletes_chep', models.PositiveIntegerField(default=0)),
                ('paletes_descartavel', models.PositiveIntegerField(default=0)),
                ('descricao', models.TextField(blank=True, default='')),
                ('responsavel', models.CharField(blank=True, default='', max_length=160)),
                ('status', models.CharField(default='aberta', max_length=20)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_devolucoes',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TmsTelemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ocorreu_em', models.DateTimeField()),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='painel.tmsviagem')),
            ],
            options={
                'db_table': 'tms_telemetria',
                'ordering': ['-ocorreu_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YmsMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_codigo', models.CharField(default='806', max_length=7)),
                ('placa', models.CharField(max_length=20)),
                ('transportadora', models.CharField(blank=True, default='', max_length=160)),
                ('motorista', models.CharField(blank=True, default='', max_length=160)),
                ('nota_fiscal', models.CharField(blank=True, default='', max_length=40)),
                ('tipo_operacao', models.CharField(default='descarregamento', max_length=30)),
                ('fluxo', models.CharField(default='expedicao', max_length=30)),
                ('status', models.CharField(default='aguardando_doca', max_length=40)),
                ('chegada_em', models.DateTimeField()),
                ('doca_atribuida_em', models.DateTimeField(blank=True, null=True)),
                ('saida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('doca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='painel.ymsdoca')),
            ],
            options={
                'db_table': 'yms_movimentacoes',
                'ordering': ['chegada_em', 'id'],
            },
        ),
        migrations.RunPython(seed_krill_telas, migrations.RunPython.noop),
    ]
