# Generated by Django 6.0.6 on 2026-09-30 17:58

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_fase2(apps, schema_editor):
    Romaneio = apps.get_model("painel", "TmsRomaneio")
    if Romaneio.objects.filter(numero_romaneio="ROM-806-004").exists():
        return
    Nfe = apps.get_model("painel", "TmsRomaneioNfe")
    Rascunho = apps.get_model("painel", "TmsRascunho")
    RascunhoNfe = apps.get_model("painel", "TmsRascunhoNfe")
    Dispositivo = apps.get_model("painel", "LogisticaDispositivo")
    hoje = timezone.localdate()
    carga = Romaneio.objects.create(
        numero_romaneio="ROM-806-004",
        data=hoje,
        hora="10:05",
        cd_origem="806",
        loja_destino="LJ-EX-OK Krill Centro",
        motorista="Carlos Souza",
        placa="ABC1D23",
        quantidade_nfes=2,
        valor_total_carga=3200,
        total_paletes=4,
        paletes_pbr=4,
        status="rascunho",
        lacres="1000001 1000002 1000003",
    )
    Nfe.objects.create(romaneio=carga, chave_acesso="3" * 44, numero="101", serie="1", status_conferencia="pendente")
    Nfe.objects.create(romaneio=carga, chave_acesso="4" * 44, numero="102", serie="1", status_conferencia="pendente")
    rascunho = Rascunho.objects.create(status="pendente_conferencia", cd_origem="806", loja_destino="Krill Centro")
    RascunhoNfe.objects.create(rascunho=rascunho, chave_acesso="5" * 44)
    Dispositivo.objects.create(identificador="cel-carlos", nome="Celular Carlos", tipo="celular", motorista="Carlos Souza", ativo=True)


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0072_tms_krill_telas'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticaDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=80, unique=True)),
                ('nome', models.CharField(blank=True, default='', max_length=160)),
                ('tipo', models.CharField(default='celular', max_length=40)),
                ('motorista', models.CharField(blank=True, default='', max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logistica_dispositivos',
                'ordering': ['nome', 'identificador'],
            },
        ),
        migrations.CreateModel(
            name='TmsMdfeManifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40)),
                ('serie', models.CharField(default='1', max_length=8)),
                ('status', models.CharField(default='rascunho', max_length=20)),
                ('data_emissao', models.DateField()),
                ('emitente_razao_social', models.CharField(blank=True, default='', max_length=180)),
                ('emitente_cnpj', models.CharField(blank=True, default='', max_length=14)),
                ('emitente_ie', models.CharField(blank=True, default='', max_length=20)),
                ('uf_carregamento', models.CharField(blank=True, default='', max_length=2)),
                ('uf_descarregamento', models.CharField(blank=True, default='', max_length=2)),
                ('motorista_nome', models.CharField(blank=True, default='', max_length=160)),
                ('motorista_cpf', models.CharField(blank=True, default='', max_length=11)),
                ('placa', models.CharField(blank=True, default='', max_length=20)),
                ('rntrc', models.CharField(blank=True, default='', max_length=20)),
                ('lacres', models.CharField(blank=True, default='', max_length=240)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('atualizado_por', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_mdfe_manifestos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TmsRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pendente_conferencia', max_length=40)),
                ('cd_origem', models.CharField(default='806', max_length=7)),
                ('loja_destino', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'romaneios_rascunhos',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='comprovante_entrega',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='tmsviagem',
            name='status_logistico',
            field=models.CharField(choices=[('em_patio', 'Em pátio'), ('em_transito', 'Em trânsito'), ('em_transporte', 'Em transporte'), ('em_descarregamento', 'Em descarregamento'), ('em_transito_retorno', 'Em trânsito de retorno'), ('entregue', 'Entregue'), ('retornou_base', 'Retornou à base')], default='em_patio', max_length=40),
        ),
        migrations.CreateModel(
            name='TmsContaPalete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_origem', models.CharField(blank=True, default='', max_length=7)),
                ('filial', models.CharField(blank=True, default='', max_length=160)),
                ('paletes_pbr_enviados', models.PositiveIntegerField(default=0)),
                ('paletes_descartaveis_enviados', models.PositiveIntegerField(default=0)),
                ('paletes_pbr_devolvidos', models.PositiveIntegerField(default=0)),
                ('paletes_descartaveis_devolvidos', models.PositiveIntegerField(default=0)),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('romaneio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_palete', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'conta_corrente_paletes_rede',
            },
        ),
        migrations.CreateModel(
            name='TmsExcecaoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40)),
                ('justificativa', models.TextField()),
                ('usuario', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_excecoes_operacionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TmsRascunhoNfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44)),
                ('rascunho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfes', to='painel.tmsrascunho')),
            ],
            options={
                'db_table': 'tms_romaneio_email_nfes',
            },
        ),
        migrations.CreateModel(
            name='TmsRomaneioNfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(db_index=True, max_length=44)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('serie', models.CharField(blank=True, default='1', max_length=8)),
                ('status_conferencia', models.CharField(default='pendente', max_length=20)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfes', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_romaneio_nfes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TmsMdfeRomaneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='painel.tmsmdfemanifesto')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdfes', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_mdfe_romaneios',
                'constraints': [models.UniqueConstraint(fields=('manifesto', 'romaneio'), name='mdfe_romaneio_unico')],
            },
        ),
        migrations.RunPython(seed_fase2, migrations.RunPython.noop),
    ]
