# Generated by Django 6.0.6 on 2026-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0073_tms_fase2_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsromaneio',
            name='valor_acumulado_bluesoft',
            field=models.FloatField(default=0),
        ),
    ]
