# Generated by Django 6.0.6 on 2026-09-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0074_valor_acumulado_bluesoft'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
