# Generated by Django 6.0.6 on 2026-09-30 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0075_nfe_valor_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmsLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='LOJA', max_length=10)),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=180)),
                ('endereco', models.CharField(blank=True, default='', max_length=240)),
                ('cep', models.CharField(blank=True, default='', max_length=12)),
                ('cnpj', models.CharField(db_index=True, max_length=14)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tms_locais',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TmsRomaneioPrevia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('criado_por', models.CharField(max_length=160)),
                ('payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tms_romaneio_import_drafts',
            },
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='cep_loja',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='cidade_loja',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='destinatario_cnpj',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='peso_bruto_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tmsromaneio',
            name='total_volumes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='arquivo_nome',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='classificacao_palete',
            field=models.CharField(blank=True, default='PBR', max_length=20),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='data_emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='descartavel_automatico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='destinatario_cnpj',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='emitente_cnpj',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='peso_bruto_kg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tmsromaneionfe',
            name='total_volumes',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='TmsRomaneioLacreFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=180)),
                ('mime_type', models.CharField(max_length=40)),
                ('tamanho_bytes', models.PositiveIntegerField(default=0)),
                ('conteudo', models.BinaryField()),
                ('criado_por', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('romaneio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto_lacres', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_romaneio_lacre_fotos',
            },
        ),
        migrations.CreateModel(
            name='TmsRomaneioProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=44)),
                ('ean', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, default='', max_length=180)),
                ('quantidade', models.FloatField(default=0)),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='painel.tmsromaneio')),
            ],
            options={
                'db_table': 'tms_romaneio_nf_produtos',
                'constraints': [models.UniqueConstraint(fields=('romaneio', 'chave_acesso', 'ean'), name='tms_romaneio_produto_unico')],
            },
        ),
    ]
