from dataclasses import dataclass

from . import models


@dataclass(frozen=True)
class ModuleConfig:
    key: str
    title: str
    menu: str
    icon: str
    model: object
    fields: tuple
    list_display: tuple
    description: str = ""
    permission: str = ""

    @property
    def perm(self):
        return self.key


MODULES = [
    ModuleConfig(
        "pendencias",
        "Pendências do Dia",
        "Painel",
        "!",
        models.Pendencia,
        ("data", "setor", "descricao", "responsavel", "status", "observacao"),
        ("data", "setor", "descricao", "responsavel", "status"),
        "Combinados, pontos pendentes e tarefas administrativas por CD.",
        "painel",
    ),
    ModuleConfig(
        "recebimento_agenda",
        "Agenda de Recebimento",
        "Recebimento",
        "A",
        models.RecebimentoAgenda,
        ("data", "empresa", "tipo_caminhao", "paletes", "agendado", "periodo", "observacao"),
        ("data", "empresa", "tipo_caminhao", "paletes", "agendado", "periodo"),
        "Veículos previstos, empresas, tipo de caminhão e paletes.",
        "recebimento",
    ),
    ModuleConfig(
        "recebimentos",
        "Recebimentos",
        "Recebimento",
        "R",
        models.Recebimento,
        ("data", "fornecedor", "nota_fiscal", "produto", "quantidade", "paletes", "motorista", "agendado", "forma_pagamento", "valor", "observacao"),
        ("data", "fornecedor", "nota_fiscal", "produto", "paletes", "agendado", "forma_pagamento", "valor"),
        "Registro de NFs, motoristas, pagamentos e paletes recebidos.",
        "recebimento",
    ),
    ModuleConfig(
        "prestadores",
        "Prestadores",
        "Prestadores",
        "P",
        models.Prestador,
        ("data", "empresa", "responsavel", "tarefa", "entrada", "saida", "status", "observacao"),
        ("data", "empresa", "responsavel", "tarefa", "entrada", "saida", "status"),
        "Controle de prestadores de serviço e tarefas realizadas.",
    ),
    ModuleConfig(
        "recebimento_conferentes",
        "Eficiência no Recebimento",
        "Recebimento",
        "EC",
        models.RecebimentoConferente,
        ("data", "conferente", "paletes", "cargas", "minutos_trabalhados", "sem_agendamento", "observacao"),
        ("data", "conferente", "paletes", "cargas", "minutos_trabalhados", "sem_agendamento"),
        "Paletes, cargas e tempo por conferente para medir eficiência no recebimento.",
        "recebimento",
    ),
    ModuleConfig(
        "colaboradores_hub",
        "Gestão de Colaboradores",
        "Colaboradores",
        "GC",
        models.ColaboradorFerias,
        (),
        (),
        "Central de férias, quadro do dia, gargalos e alertas de colaboradores.",
        "colaboradores_hub",
    ),
    ModuleConfig(
        "funcoes_turno",
        "Funções do Turno",
        "Colaboradores",
        "FT",
        models.FuncaoTurno,
        ("nome", "setor", "setor_detalhado", "turno", "quadro_padrao", "ativa", "observacao"),
        ("nome", "setor", "setor_detalhado", "turno", "quadro_padrao", "ativa"),
        "Cadastro das funções usadas em Pessoas no Turno.",
        "funcoes_turno",
    ),
    ModuleConfig(
        "pessoas_turno",
        "Pessoas no Turno",
        "Colaboradores",
        "PT",
        models.PessoaTurno,
        ("data", "setor", "setor_detalhado", "turno", "funcao", "quadro_atual", "planejado", "ativos_dia", "atestados", "afastados", "ferias", "folgas", "faltas_sem_justificativa", "observacao"),
        ("data", "setor", "setor_detalhado", "turno", "funcao", "quadro_atual", "planejado", "ativos_dia", "atestados", "afastados", "ferias", "folgas", "faltas_sem_justificativa"),
        "Quadro planejado e presenças por função para o relatório de abertura.",
        "pessoas_turno",
    ),
    ModuleConfig(
        "ferias_colaboradores",
        "Férias dos Colaboradores",
        "Colaboradores",
        "FE",
        models.ColaboradorFerias,
        ("data", "colaborador", "setor", "setor_detalhado", "funcao", "inicio_ferias", "fim_ferias", "retorno_previsto", "status", "notificar_supervisor", "observacao"),
        ("colaborador", "setor", "setor_detalhado", "funcao", "inicio_ferias", "fim_ferias", "retorno_previsto", "status", "notificar_supervisor"),
        "Controle de férias por colaborador, com alertas para supervisão.",
        "ferias_colaboradores",
    ),
    ModuleConfig(
        "ausencias_colaboradores",
        "Ausências dos Colaboradores",
        "Colaboradores",
        "AU",
        models.ColaboradorAusencia,
        ("data", "colaborador", "setor", "setor_detalhado", "funcao", "tipo", "inicio", "fim", "status", "notificar_supervisor", "observacao"),
        ("colaborador", "setor", "setor_detalhado", "funcao", "tipo", "inicio", "fim", "status", "notificar_supervisor"),
        "Atestados, afastamentos, faltas e folgas que impactam a operação e a frota.",
        "ausencias_colaboradores",
    ),
    ModuleConfig(
        "equipamentos",
        "Equipamentos",
        "Equipamentos",
        "E",
        models.Equipamento,
        ("data", "colaborador", "setor", "tipo", "equipamento", "patrimonio", "coletor_tipo", "status", "observacao"),
        ("data", "colaborador", "setor", "tipo", "equipamento", "patrimonio", "coletor_tipo", "status"),
        "Paleteiras, coletores, computadores e empilhadeiras por colaborador.",
    ),
    ModuleConfig(
        "manutencao_equipamentos",
        "Manutenção de Equipamentos",
        "Equipamentos",
        "TI",
        models.EquipamentoManutencao,
        ("data", "equipamento_cadastrado", "problema", "destino", "responsavel", "data_retorno", "status", "observacao"),
        ("data", "patrimonio", "equipamento", "tipo", "destino", "status", "data_retorno"),
        "Histórico de ida ao TI, manutenção interna ou fornecedor por patrimônio.",
        "equipamentos",
    ),
    ModuleConfig(
        "materiais",
        "Materiais de Consumo",
        "Materiais",
        "M",
        models.MaterialConsumo,
        ("data", "material", "categoria", "estoque_atual", "estoque_minimo", "unidade", "fornecedor", "observacao"),
        ("data", "material", "categoria", "estoque_atual", "estoque_minimo", "unidade", "precisa_pedir"),
        "Controle de materiais e lista automática do que precisa pedir.",
    ),
    ModuleConfig(
        "conferencias",
        "Conferência",
        "Conferência",
        "C",
        models.Conferencia,
        ("data", "setor", "loja", "gtin", "produto", "qtd_esperada", "qtd_conferida", "status", "responsavel", "observacao"),
        ("data", "setor", "loja", "produto", "qtd_esperada", "qtd_conferida", "diferenca", "status"),
        "Conferências por produto, divergências e responsáveis.",
    ),
    ModuleConfig(
        "avarias",
        "Avarias",
        "Avarias",
        "V",
        models.Avaria,
        ("data", "gtin", "produto", "validade", "lote", "tipo", "origem", "caixas", "unidades", "valor_estimado", "destino", "status", "responsavel", "observacao"),
        ("data", "produto", "validade", "tipo", "caixas", "unidades", "valor_estimado", "status"),
        "Vencidos, sobras, avarias em caixa/unidade e destino.",
    ),
    ModuleConfig(
        "chamados_saldo",
        "Sem Saldo GLPI",
        "GLPI",
        "G",
        models.ChamadoSaldo,
        ("data", "gtin", "produto", "endereco", "saldo_sistema", "saldo_fisico", "tipo_chamado", "prioridade", "numero_glpi", "status", "responsavel", "observacao"),
        ("data", "produto", "endereco", "saldo_sistema", "saldo_fisico", "diferenca", "tipo_chamado", "numero_glpi", "status"),
        "Produtos sem saldo e chamados para ganho/quebra/ajuste.",
    ),
    ModuleConfig(
        "unitizadores",
        "Unitizadores",
        "Unitizadores",
        "U",
        models.Unitizador,
        ("data", "loja", "quantidade", "tipo_unitizador", "status", "data_retorno", "observacao"),
        ("data", "loja", "quantidade", "tipo_unitizador", "status", "data_retorno"),
        "Controle de envio e retorno de unitizadores por loja.",
    ),
    ModuleConfig(
        "paletes_vasilhames",
        "Paletes e Vasilhames",
        "Unitizadores",
        "PV",
        models.ControlePaleteVasilhame,
        (
            "data",
            "turno",
            "responsavel",
            "palete_pbr",
            "palete_chep",
            "palete_chapatex",
            "palete_descartavel",
            "vasilhame_coca",
            "vasilhame_cerveja",
            "palete_cheio",
            "palete_vazio",
            "observacao",
        ),
        (
            "data",
            "turno",
            "responsavel",
            "palete_pbr",
            "palete_chep",
            "palete_chapatex",
            "palete_descartavel",
            "vasilhame_coca",
            "vasilhame_cerveja",
            "palete_cheio",
            "palete_vazio",
        ),
        "Lancamento rapido de PBR, CHEP, Chapatex, descartaveis, vasilhames e paletes cheios/vazios.",
        "unitizadores",
    ),
    ModuleConfig(
        "paletes_rede",
        "Pallets da Rede",
        "Operação CD",
        "PR",
        models.PaleteRedeSaldo,
        ("data", "local_tipo", "local_codigo", "local_nome", "tipo_palete", "quantidade", "quebrados", "reservados", "responsavel", "observacao"),
        ("local_tipo", "local_codigo", "local_nome", "tipo_palete", "quantidade", "quebrados", "reservados", "disponivel"),
        "Controle de PBR, CHEP, descartaveis e PBR 2 por CD, loja e rede, com reservas e transferencias.",
        "paletes_rede",
    ),
    ModuleConfig(
        "separacao",
        "Separação",
        "Separação",
        "S",
        models.Separacao,
        ("data", "loja", "categoria", "setor", "unidades", "paletes", "onda_gerada", "total_a_produzir", "crossdocking_produzido", "separacao_pulmao_produzido", "separacao_picking_produzido", "recursos_picking", "horas_picking", "recursos_pulmao", "horas_pulmao", "responsavel", "status", "observacao"),
        ("data", "loja", "categoria", "unidades", "paletes", "separacao_pulmao_produzido", "separacao_picking_produzido", "responsavel", "status"),
        "Separação por loja/categoria com produtividade no mesmo lançamento.",
    ),
    ModuleConfig(
        "ressuprimento",
        "Ressuprimento",
        "Ressuprimento",
        "RS",
        models.Ressuprimento,
        ("data", "gtin", "produto", "endereco_origem", "endereco_destino", "quantidade", "responsavel", "status", "observacao"),
        ("data", "gtin", "produto", "endereco_origem", "endereco_destino", "quantidade", "responsavel", "status"),
        "Ressuprimentos preparados para uso com GTIN importado.",
    ),
    ModuleConfig(
        "ressuprimento_painel",
        "Painel Ressuprimento",
        "Ressuprimento",
        "RP",
        models.RessuprimentoPainel,
        ("data", "tipo_painel", "setor", "area", "rua", "local_estoque", "atividade", "qtd_itens", "qtd_volume", "pendencia_itens", "pendencia_volume", "produzido_itens", "produzido_volume", "picking", "pulmao", "observacao"),
        ("data", "tipo_painel", "setor", "area", "rua", "local_estoque", "atividade", "qtd_itens", "qtd_volume", "pendencia_itens", "produzido_volume"),
        "Dados por setor, área, rua, local e atividade para demanda, ocupação e produção do ressuprimento.",
        "ressuprimento",
    ),
    ModuleConfig(
        "separacao_produtividade",
        "Produtividade Separação",
        "Separação",
        "PS",
        models.SeparacaoProdutividade,
        ("data", "setor", "onda_gerada", "total_a_produzir", "crossdocking_produzido", "separacao_pulmao_produzido", "separacao_picking_produzido", "recursos_picking", "horas_picking", "recursos_pulmao", "horas_pulmao", "observacao"),
        ("data", "setor", "onda_gerada", "total_a_produzir", "separacao_pulmao_produzido", "separacao_picking_produzido"),
        "Onda, produção, recursos e horas para calcular produtividade de picking e pulmão.",
        "separacao",
    ),
    ModuleConfig(
        "expedicao_planejamento",
        "Saldo de Pallets",
        "Expedição",
        "PC",
        models.ExpedicaoPlanejamento,
        ("loja", "qtd_paletes", "observacao"),
        ("data", "loja", "qtd_paletes"),
        "Informe ou corrija quantos pallets cada loja ainda tem na expedicao.",
    ),
    ModuleConfig(
        "carregamento_veiculos",
        "Enviar Caminhao",
        "Frota",
        "CV",
        models.ExpedicaoPlanejamento,
        ("loja", "qtd_paletes", "observacao"),
        ("data", "loja", "qtd_paletes"),
        "Defina motorista e placa para lojas que vao carregar.",
    ),
    ModuleConfig(
        "aprovacoes_carregamento",
        "Excecoes de Carregamento",
        "Frota",
        "AC",
        models.SolicitacaoCarregamentoManual,
        ("data", "loja", "qtd_paletes", "placa", "motorista", "periodo", "status", "motivo", "resposta"),
        ("data", "cd_unidade", "loja", "qtd_paletes", "placa", "motorista", "periodo", "status"),
        "Frota aprova ou recusa pedidos fora do fluxo normal.",
    ),
    ModuleConfig(
        "solicitar_lancamento_manual_expedicao",
        "Pedir Excecao de Carregamento",
        "Expedição",
        "SM",
        models.SolicitacaoCarregamentoManual,
        ("data", "loja", "qtd_paletes", "placa", "motorista", "periodo", "motivo"),
        ("data", "cd_unidade", "loja", "qtd_paletes", "placa", "motorista", "periodo", "status"),
        "Expedicao pede liberacao quando precisa carregar fora do fluxo normal.",
    ),
    ModuleConfig(
        "lojas_prontas_carregamento",
        "Lojas Prontas para Carregar",
        "Expedição",
        "LP",
        models.SolicitacaoCargaPronta,
        ("data", "loja", "qtd_paletes", "periodo", "observacao"),
        ("data", "cd_unidade", "loja", "qtd_paletes", "periodo", "status"),
        "Aviso operacional da Expedição para a Frota informando que uma loja já está pronta para carregar.",
    ),
    ModuleConfig(
        "solicitacao_caminhoes",
        "Solicitação de Caminhões",
        "Frota",
        "SC",
        models.SolicitacaoCaminhaoCD,
        (),
        ("data", "cd_unidade", "cd_destino", "data_necessidade", "qtd_caminhoes", "periodo", "status"),
        "CD 806 solicita para a Frota a quantidade de caminhões necessária para o dia seguinte.",
    ),
    ModuleConfig(
        "faturamento_expedicao",
        "Faturamento BlueSoft",
        "Expedição",
        "NF",
        models.ExpedicaoFaturamento,
        ("data", "loja", "placa", "motorista", "qtd_paletes", "valor_carga", "periodo", "carga_bluesoft", "nota_fiscal", "chave_acesso", "status", "motivo_fiscal", "observacao"),
        ("data", "cd_unidade", "loja", "placa", "motorista", "qtd_paletes", "valor_carga", "status", "carga_bluesoft", "nota_fiscal"),
        "Assistente da Expedição registra valor faturado, carga BlueSoft e liberação fiscal por loja.",
    ),
    ModuleConfig(
        "expedicao",
        "Expedição",
        "Expedição",
        "X",
        models.Expedicao,
        ("data", "loja", "placa", "motorista", "qtd_paletes", "periodo", "status", "observacao"),
        ("data", "loja", "placa", "motorista", "qtd_paletes", "periodo", "status"),
        "Execução do carregamento por loja, motorista e placa, com baixa automática no saldo de pallets.",
    ),
    ModuleConfig(
        "relatorio_paletes_cd",
        "Resumo de Pallets",
        "Expedição",
        "RP",
        models.ExpedicaoPlanejamento,
        ("loja", "qtd_paletes", "observacao"),
        ("data", "loja", "qtd_paletes"),
        "Acompanhe saldo, reservado e expedido por loja e CD.",
        "expedicao_planejamento",
    ),
    ModuleConfig(
        "checklist_frota",
        "Check-list do Motorista",
        "Frota",
        "FR",
        models.ChecklistFrota,
        (
            "data",
            "tipo_checklist",
            "motorista",
            "veiculo",
            "placa",
            "loja_destino",
            "intercala_cd",
            "cd_intercalacao",
            "intercalacao_concluida",
            "observacao_intercalacao",
            "km_inicial",
            "km_final",
            "horario_saida",
            "horario_chegada_loja",
            "horario_saida_loja",
            "horario_retorno",
            "carga_retorno",
            "carga_retorno_descricao",
            "documentacao_veiculo_ok",
            "documentacao_veiculo_obs",
            "cnh_motorista_ok",
            "cnh_motorista_obs",
            "documento_motorista_ok",
            "documento_motorista_obs",
            "tacografo_ok",
            "tacografo_obs",
            "rastreador_ok",
            "rastreador_obs",
            "pneus_ok",
            "pneus_obs",
            "calibragem_pneus_ok",
            "calibragem_pneus_obs",
            "estepe_ok",
            "estepe_obs",
            "macaco_chave_ok",
            "macaco_chave_obs",
            "triangulo_ok",
            "triangulo_obs",
            "extintor_ok",
            "extintor_obs",
            "cintos_ok",
            "cintos_obs",
            "farois_ok",
            "farois_obs",
            "lanternas_ok",
            "lanternas_obs",
            "luz_freio_ok",
            "luz_freio_obs",
            "setas_ok",
            "setas_obs",
            "luz_re_ok",
            "luz_re_obs",
            "limpador_para_brisa_ok",
            "limpador_para_brisa_obs",
            "agua_limpador_ok",
            "agua_limpador_obs",
            "buzina_ok",
            "buzina_obs",
            "retrovisores_ok",
            "retrovisores_obs",
            "lataria_ok",
            "lataria_obs",
            "freios_ok",
            "freios_obs",
            "embreagem_ok",
            "embreagem_obs",
            "direcao_ok",
            "direcao_obs",
            "suspensao_ok",
            "suspensao_obs",
            "bateria_ok",
            "bateria_obs",
            "vazamentos_ok",
            "vazamentos_obs",
            "combustivel_ok",
            "combustivel_obs",
            "arla_ok",
            "arla_obs",
            "oleo_motor_ok",
            "oleo_motor_obs",
            "agua_radiador_ok",
            "agua_radiador_obs",
            "cabine_limpa_saida_ok",
            "cabine_limpa_saida_obs",
            "bau_limpo_saida_ok",
            "bau_limpo_saida_obs",
            "vedacao_bau_ok",
            "vedacao_bau_obs",
            "portas_travas_ok",
            "portas_travas_obs",
            "pane_mecanica",
            "furo_pneu",
            "acidente",
            "multa",
            "avaria_carga",
            "vazamento_viagem",
            "outra_ocorrencia",
            "descricao_ocorrencia",
            "ocorrencia_rota_loja",
            "veiculo_limpo_retorno_ok",
            "veiculo_limpo_retorno_obs",
            "bau_limpo_retorno_ok",
            "bau_limpo_retorno_obs",
            "combustivel_informado_ok",
            "combustivel_informado_obs",
            "novas_avarias_ok",
            "novas_avarias_obs",
            "pneus_sem_danos_ok",
            "pneus_sem_danos_obs",
            "documentacao_entregue_ok",
            "documentacao_entregue_obs",
            "chaves_devolvidas_ok",
            "chaves_devolvidas_obs",
            "necessita_manutencao",
            "descricao_manutencao",
            "responsavel_frota",
            "observacao",
        ),
        (
            "data",
            "cd_unidade",
            "tipo_checklist",
            "status_intercalacao",
            "motorista",
            "veiculo",
            "placa",
            "loja_destino",
            "carga_retorno",
            "km_inicial",
            "km_final",
            "tempo_cd_ate_loja",
            "tempo_na_loja",
            "tempo_loja_ate_cd",
            "tempo_total_viagem",
            "necessita_manutencao",
            "responsavel_frota",
        ),
        "Check-list diario de saida, viagem, retorno e manutencao da frota.",
        "checklist_frota",
    ),
    ModuleConfig(
        "veiculos_frota",
        "Motoristas, Placas e Status",
        "Frota",
        "MP",
        models.VeiculoFrota,
        ("data", "motorista", "placa", "tipo_caminhao", "plataforma_operacional", "tacografo_frequencia", "status_operacional", "local_atual", "orientacao_frota", "usuario_motorista", "ativo", "observacao"),
        ("motorista", "placa", "tipo_caminhao", "plataforma_operacional", "tacografo_frequencia", "status_operacional", "local_atual", "usuario_motorista", "ativo"),
        "Cadastro de motoristas e placas para preencher a expedicao com menos digitacao.",
    ),
    ModuleConfig(
        "escala_veiculos_frota",
        "Escala de Motoristas",
        "Frota",
        "EV",
        models.EscalaVeiculoFrota,
        ("data", "placa", "motorista_titular", "motorista_responsavel", "usuario_responsavel", "inicio", "fim", "motivo", "ativo", "observacao"),
        ("placa", "motorista_titular", "motorista_responsavel", "inicio", "fim", "motivo", "ativo"),
        "Define quem está responsável por uma placa durante férias, manutenção ou troca operacional.",
    ),
    ModuleConfig(
        "materiais_frota",
        "Materiais da Frota",
        "Frota",
        "MF",
        models.MaterialFrota,
        ("data", "material", "tipo_material", "condicao", "movimento", "quantidade", "placa", "patrimonio", "localizacao", "responsavel", "observacao"),
        ("data", "material", "tipo_material", "condicao", "movimento", "quantidade", "placa", "localizacao", "responsavel"),
        "Lista de pecas, ferramentas e materiais bons, quebrados ou aguardando reparo.",
        "materiais_frota",
    ),
    ModuleConfig(
        "checklist_frota_itens",
        "Itens do Check-list Frota",
        "Frota",
        "IC",
        models.ChecklistFrotaItem,
        ("data", "grupo_config", "grupo", "titulo", "tipo_checklist", "ordem", "frequencia", "ativo", "obrigatorio", "observacao"),
        ("grupo", "titulo", "tipo_checklist", "ordem", "frequencia", "ativo", "obrigatorio"),
        "Itens adicionais configuráveis pelo supervisor para aparecer no check-list dos motoristas.",
        "checklist_frota_itens",
    ),
    ModuleConfig(
        "lacres_frota",
        "Ocorrências de Lacres",
        "Frota",
        "LC",
        models.LacreFrota,
        ("data", "motorista", "placa", "loja_destino", "lacre", "cd_lacre", "motivo", "descricao", "status", "tratado_por", "observacao"),
        ("data", "cd_unidade", "motorista", "placa", "loja_destino", "lacre", "cd_lacre", "motivo", "status"),
        "Registro de erro de lacre informado pelo motorista, com acompanhamento pela frota.",
        "lacres_frota",
    ),
    ModuleConfig(
        "ocorrencias",
        "Ocorrências Operacionais",
        "Gestão",
        "OC",
        models.OcorrenciaOperacional,
        ("data", "tipo", "setor", "titulo", "descricao", "origem", "referencia", "severidade", "status", "recorrente", "responsavel", "solucao", "observacao"),
        ("data", "tipo", "setor", "titulo", "severidade", "status", "recorrente", "responsavel"),
        "Central única de problemas da operação: frota, avarias, equipamentos, GLPI, pessoas e rotina do CD.",
        "ocorrencias",
    ),
    ModuleConfig(
        "aprovacoes",
        "Aprovações",
        "Gestão",
        "AP",
        models.AprovacaoOperacional,
        ("data", "setor", "titulo", "descricao", "referencia", "solicitante", "nivel_necessario", "status", "justificativa", "observacao"),
        ("data", "setor", "titulo", "solicitante", "nivel_necessario", "status"),
        "Fluxo de validação para o que precisa de supervisor ou gerente.",
        "aprovacoes",
    ),
    ModuleConfig(
        "fechamentos",
        "Fechamento do Dia",
        "Gestão",
        "FD",
        models.FechamentoDia,
        ("data", "turno", "responsavel", "recebimento_fechado", "expedicao_fechada", "frota_conferida", "pessoas_registradas", "avarias_revisadas", "pendencias_amanha", "status", "resumo_gerencial", "observacao"),
        ("data", "turno", "responsavel", "status", "recebimento_fechado", "expedicao_fechada", "frota_conferida"),
        "Checklist de fechamento do CD com resumo gerencial automatico.",
        "fechamento_cd",
    ),
    ModuleConfig(
        "melhorias_sistema",
        "Solicitar Melhoria",
        "Melhorias",
        "SM",
        models.MelhoriaSistema,
        (
            "data",
            "titulo",
            "tipo_solicitacao",
            "area",
            "solicitante",
            "descricao",
            "impacto",
            "prioridade",
            "status",
            "responsavel",
            "previsao",
            "decisao",
            "observacao",
        ),
        ("data", "titulo", "tipo_solicitacao", "area", "solicitante", "prioridade", "status", "responsavel", "previsao"),
        "Envio de sugestões, pedidos de implantação e oportunidades de melhoria do sistema.",
        "melhorias_sistema",
    ),
    ModuleConfig(
        "lojas",
        "Lojas da Rede",
        "Banco de Dados",
        "L",
        models.Loja,
        ("codigo", "nome", "grupo", "loja_plataforma", "empilhadeira_indisponivel", "ativa", "observacao"),
        ("codigo", "nome", "grupo", "loja_plataforma", "empilhadeira_indisponivel", "ativa"),
        "Cadastro das lojas por CD.",
        "banco_dados",
    ),
    ModuleConfig(
        "gtins",
        "GTINs e Produtos",
        "Banco de Dados",
        "B",
        models.ProdutoGtin,
        ("gtin", "descricao", "categoria", "embalagem", "endereco", "ativo", "observacao"),
        ("gtin", "descricao", "categoria", "embalagem", "endereco", "ativo"),
        "Base de produtos para ressuprimento e conferência.",
        "banco_dados",
    ),
    ModuleConfig(
        "parametros_cd",
        "Parâmetros por CD",
        "Banco de Dados",
        "PC",
        models.ParametroCD,
        ("tipo", "codigo", "nome", "ordem", "ativo", "observacao"),
        ("cd_unidade", "tipo", "codigo", "nome", "ordem", "ativo"),
        "Cadastro de áreas, ruas, locais de estoque e atividades separado por CD.",
        "banco_dados",
    ),
]

MODULE_BY_KEY = {module.key: module for module in MODULES}

ALL_PERMISSIONS = [
    ("painel", "Tela - Início: abrir a tela inicial do sistema"),
    ("painel_gestao", "Tela - Painel Gerencial: ver resumo do CD, frota, expedicao e ferias"),
    ("sentinela_servidor", "Tela - Sentinela do servidor: manter o Render acordado"),
    ("painel_master", "Tela - Painel Master: recursos exclusivos do master"),
    ("auditoria_acessos", "Tela - Auditoria: ver logins, senhas e alterações de acesso"),
    ("relatorios", "Tela - Relatorios: imprimir ou exportar dados do sistema"),
    ("preferencias", "Tela - Minha tela: ocultar painéis do próprio usuário"),
    ("gestao_acesso", "Tela - Gestão de acesso: cadastrar e alterar usuários"),
    ("gestao_acesso_total", "Ação - Gestão total: liberar permissões sensíveis de acesso"),
    ("personalizar_interface", "Tela - Organizar telas: criar centrais, cards, nomes e icones"),
    ("modo_demonstracao", "Ferramenta - Modo demonstracao: simular acoes sem gravar no banco real"),
    ("importar_planilhas", "Tela - Importar planilhas: trazer bases externas"),
    ("corrigir_cd", "Tela - Corrigir CD: ajustar registros lançados no CD errado"),
    ("alertas_frota", "Alerta - Frota: ver botão flutuante de alertas da frota"),
    ("alertas_ferias", "Alerta - Férias: ver botão flutuante de alertas de colaboradores"),
    ("notificacoes_ferias_colaboradores", "Notificação - Colaboradores: receber alertas de férias, retorno e ausência"),
    ("setores_detalhados_colaboradores", "Recurso - Colaboradores: usar setores/ruas detalhados"),
    ("mapa_calor_ferias", "Tela - Mapa de calor: ver pressão de férias por setor"),
    ("capacidade_operacao", "Tela - Capacidade: acompanhar efetivo, ausências e gargalos"),
    ("configurar_alertas_ferias", "Tela - Configurar alertas: ajustar regras de férias e ausência"),
    ("visualizar_gargalos_colaboradores", "Consulta - Colaboradores: ver gargalos calculados pelo sistema"),
    ("gerenciar_ferias_colaboradores", "Ação - Colaboradores: cadastrar/editar férias e ausências"),
    ("saude_equipamentos", "Consulta - Equipamentos: ver indicadores de manutenção e reincidência"),
    ("pendencias", "Tela - Pendências do Dia: registrar pendências operacionais"),
    ("recebimento_agenda", "Tela - Agenda de Recebimento: cadastrar veículos agendados"),
    ("recebimentos", "Tela - Recebimentos: registrar notas, paletes e valores recebidos"),
    ("prestadores", "Tela - Prestadores: registrar serviços no CD"),
    ("colaboradores_hub", "Tela - Colaboradores: abrir a central de pessoas, férias e capacidade"),
    ("pessoas_turno", "Tela - Pessoas no Turno: registrar efetivo por setor"),
    ("funcoes_turno", "Tela - Funções do Turno: configurar funções por setor"),
    ("ferias_colaboradores", "Tela - Férias dos Colaboradores: cadastrar férias e acompanhar calendário"),
    ("ausencias_colaboradores", "Tela - Ausências dos Colaboradores: registrar faltas e atestados"),
    ("recebimento_conferentes", "Tela - Eficiência Recebimento: acompanhar conferentes"),
    ("conferencias", "Tela - Conferência: registrar controle de conferência"),
    ("unitizadores", "Tela - Unitizadores: controlar datas e uso"),
    ("paletes_vasilhames", "Tela - Paletes e Vasilhames: controlar entradas e saídas"),
    ("paletes_rede", "Tela - Pallets da Rede: ver PBR, CHEP, descartaveis e PBR 2 por CD e loja"),
    ("adicionar_loja_paletes_rede", "Acao - Pallets da Rede: adicionar loja no controle"),
    ("editar_saldo_paletes_rede", "Acao - Pallets da Rede: corrigir quantidade de um CD ou loja"),
    ("movimentar_paletes_rede", "Acao - Pallets da Rede: reservar ou confirmar retirada para fornecedor"),
    ("separacao", "Tela - Separação: registrar separação"),
    ("ressuprimento", "Tela - Ressuprimento: registrar abastecimento de picking"),
    ("ressuprimento_painel", "Tela - Painel Ressuprimento: acompanhar indicadores de ressuprimento"),
    ("expedicao_planejamento", "Tela - Saldo de Pallets: informar ou corrigir pallets da expedicao"),
    ("carregamento_veiculos", "Tela - Enviar Caminhao: definir motorista e placa para carga"),
    ("expedicao", "Tela - Baixar Carga: confirmar o que saiu fisicamente do CD"),
    ("solicitar_lancamento_manual_expedicao", "Tela - Pedir Excecao: solicitar liberacao para carga fora do fluxo"),
    ("lojas_prontas_carregamento", "Tela - Loja Pronta: avisar a Frota que uma loja ja pode carregar"),
    ("relatorio_paletes_cd", "Tela - Resumo de Pallets: ver saldo, reservado e expedido"),
    ("equipamentos", "Tela - Equipamentos: cadastrar coletores, paleteiras, PCs e empilhadeiras"),
    ("manutencao_equipamentos", "Tela - Manutenção de Equipamentos: registrar ida ao TI/manutenção"),
    ("materiais", "Tela - Materiais: controlar materiais de consumo"),
    ("avarias", "Tela - Avarias: registrar perdas, vencidos e sobras"),
    ("chamados_saldo", "Tela - Sem saldo GLPI: registrar chamados de saldo"),
    ("checklist_frota", "Tela - Check-list do Motorista: registrar saida, loja e retorno"),
    ("checklist_frota_itens", "Tela - Regras do Check-list: editar perguntas, grupos e frequencia"),
    ("veiculos_frota", "Tela - Motoristas e Placas: cadastrar placa, motorista, plataforma e status"),
    ("escala_veiculos_frota", "Tela - Escala de Motoristas: informar troca de motorista por periodo"),
    ("materiais_frota", "Tela - Materiais da Frota: controlar materiais usados pela frota"),
    ("lacres_frota", "Tela - Ocorrências de Lacres: registrar problemas de lacre"),
    ("ocorrencias", "Tela - Ocorrências: registrar problemas operacionais"),
    ("aprovacoes", "Tela - Aprovações: acompanhar solicitações críticas"),
    ("fechamentos", "Tela - Fechamento do dia: checklist de fechamento do CD"),
    ("melhorias_sistema", "Tela - Sugestões de melhoria: enviar pedido ou ideia"),
    ("gerenciar_melhorias_sistema", "Tela - Gerenciar melhorias: responder pedidos enviados"),
    ("lojas", "Tela - Lojas da Rede: cadastrar lojas e regra de plataforma"),
    ("gtins", "Tela - GTINs e Produtos: cadastrar produtos do CD"),
    ("parametros_cd", "Tela - Parâmetros por CD: configurar regras por unidade"),
    ("criar_registros", "Ação - Criar: salvar novos registros nas telas liberadas"),
    ("consultar_registros", "Ação - Consultar: ver históricos e registros salvos"),
    ("ver_graficos_resumos", "Consulta - Resumos: ver cards, gráficos e indicadores"),
    ("painel_frota", "Tela - Painel da Frota: acompanhar checklists, retornos e ocorrências"),
    ("visualizar_cds_unificados", "Consulta - CD unificado: ver dados dos CDs 801 e 806 quando permitido"),
    ("vincular_cargas_expedicao", "Acao - Enviar Caminhao: separar motorista/placa para carregar"),
    ("aprovacoes_carregamento", "Tela - Excecoes de Carregamento: aprovar ou recusar pedidos manuais"),
    ("acompanhar_lojas_prontas_carregamento", "Consulta - Fila de Carregamento: Frota ve lojas prontas"),
    ("aprovar_lancamento_manual_expedicao", "Acao - Excecao: aprovar ou recusar carregamento manual"),
    ("lancar_manual_sem_aprovacao", "Acao sensivel - Carga direta: carregar sem aprovacao da Frota"),
    ("corrigir_saldo_paletes", "Ação - Corrigir saldo: alterar ou zerar saldo de pallets"),
    ("faturamento_expedicao", "Tela - Faturamento BlueSoft: registrar valor, carga, NF e liberação fiscal"),
    ("registrar_erro_fiscal", "Ação - Faturamento BlueSoft: registrar erro ou pendência fiscal"),
    ("liberar_carga_faturada", "Ação - Faturamento BlueSoft: marcar carga faturada/liberada"),
    ("notificar_carga_vinculada", "Notificacao - Caminhao enviado: avisar quando a Frota definir motorista"),
    ("notificar_alteracao_carga", "Notificacao - Carga alterada: avisar mudancas de motorista, placa ou quantidade"),
    ("notificar_saldo_paletes", "Notificação - Saldo de pallets: avisar saldo lançado ou corrigido"),
    ("notificar_loja_pronta_carregamento", "Notificação - Loja pronta: avisar Frota sobre loja liberada"),
    ("notificar_motorista_vinculado", "Notificacao - Motorista: avisar motorista sobre carga/tarefa"),
    ("notificar_checklist_motorista", "Notificação - Check-list: avisar supervisor sobre saída/retorno"),
    ("receber_alertas_expedicao", "Notificação - Expedição: receber alertas de cargas e confirmações"),
    ("gerenciar_push", "Tela - Gerenciar Push: testar, limpar e acompanhar aparelhos"),
    ("editar_checklist_frota", "Ação - Checklist: editar itens e regras do checklist"),
    ("encerrar_retorno_frota", "Ação - Frota: encerrar retorno pendente"),
    ("exportar_frota", "Ação - Frota: exportar dados da frota"),
    ("trocar_cd", "Ação - Trocar CD: alterar CD ativo no topo do sistema"),
    ("editar_registros", "Ação - Editar: alterar registros salvos nas telas liberadas"),
    ("excluir_registros", "Ação - Excluir: apagar registros salvos nas telas liberadas"),
    ("exportar_dados", "Ação - Exportar: baixar Excel/CSV das telas liberadas"),
    ("solicitacao_caminhoes", "Tela - Solicitação de Caminhões: pedir veículos para outro CD"),
    ("tratar_solicitacao_caminhoes", "Ação - Caminhões: responder solicitação e indicar motoristas"),
    ("notificar_solicitacao_caminhoes", "Notificação - Caminhões: avisar sobre pedido ou resposta de caminhões"),
    ("tms_expedicao", "TMS - Central de Expedição: ver viagens, capacidade e telemetria do dia"),
    ("tms_krill", "TMS/WMS/YMS - telas traduzidas do Gestão CD: romaneios, rotas, pátio, mapa e indicadores"),
]

ALL_PERMISSION_KEYS = [key for key, _label in ALL_PERMISSIONS]

LEGACY_PERMISSION_MIGRATION_MARKER = "__permissoes_individuais_v1"
LEGACY_PERMISSION_EXPANSION = {
    "painel": {"painel"},
    "recebimento": {"recebimento_agenda", "recebimentos", "recebimento_conferentes"},
    "equipamentos": {"equipamentos", "manutencao_equipamentos"},
    "unitizadores": {"unitizadores", "paletes_vasilhames", "paletes_rede", "adicionar_loja_paletes_rede", "editar_saldo_paletes_rede", "movimentar_paletes_rede"},
    "ressuprimento": {"ressuprimento", "ressuprimento_painel"},
    "banco_dados": {"lojas", "gtins", "parametros_cd"},
    "fechamento_cd": {"fechamentos"},
}

FIELD_LABELS = {
    "grupo_config": "Grupo existente",
    "campo_sistema": "Campo do sistema",
    "mostrar_motorista": "Mostrar para motorista",
    "dica": "Orientação",
    "aprovado_em": "Aprovado em",
    "aprovado_por": "Aprovado por",
    "assumido_em": "Assumido em",
    "assumido_por": "Assumido por",
    "avarias_revisadas": "Avarias revisadas",
    "expedicao_fechada": "Expedição fechada",
    "frota_conferida": "Frota conferida",
    "nivel_necessario": "Nível necessário",
    "pendencias_amanha": "Pendências para amanhã",
    "pessoas_registradas": "Pessoas registradas",
    "recebimento_fechado": "Recebimento fechado",
    "recorrente": "Recorrente",
    "referencia": "Referência",
    "resolvido_em": "Resolvido em",
    "resolvido_por": "Resolvido por",
    "resumo_gerencial": "Resumo gerencial",
    "severidade": "Severidade",
    "solicitante": "Solicitante",
    "solucao": "Solução",
    "titulo": "Título",
    "ativa": "Ativa",
    "ativo": "Ativo",
    "area": "Área",
    "atividade": "Atividade",
    "agendado": "Agendado",
    "caixas": "Caixas",
    "categoria": "Categoria",
    "cd_padrao": "CD padrão",
    "cd_unidade": "CD",
    "cd_intercalacao": "CD da passagem",
    "coletor_tipo": "Coletor/tipo",
    "codigo": "Código",
    "colaborador": "Colaborador",
    "data": "Data",
    "data_retorno": "Data de retorno",
    "descricao": "Descrição",
    "destino": "Destino",
    "diferenca": "Diferença",
    "documento": "Documento",
    "embalagem": "Embalagem",
    "empresa": "Empresa",
    "endereco": "Endereço",
    "endereco_destino": "Endereço destino",
    "endereco_origem": "Endereço origem",
    "entrada": "Entrada",
    "equipamento": "Equipamento/série",
    "estoque_atual": "Estoque atual",
    "estoque_minimo": "Estoque mínimo",
    "forma_pagamento": "Forma de pagamento",
    "fornecedor": "Fornecedor",
    "afastados": "Afastados",
    "atestados": "Atestados",
    "ativos_dia": "Ativos dia",
    "ferias": "Férias",
    "folgas": "Folgas",
    "faltas_sem_justificativa": "Faltas sem justificativa",
    "funcao": "Função",
    "gtin": "GTIN",
    "grupo": "Grupo",
    "loja": "Loja",
    "lote": "Lote",
    "localizacao": "Localização",
    "local_estoque": "Local de estoque",
    "material": "Material",
    "tipo_material": "Tipo de material",
    "condicao": "Condição",
    "movimento": "Movimento",
    "motorista": "Motorista",
    "nome": "Nome",
    "nota_fiscal": "Nota fiscal",
    "numero_glpi": "Número GLPI",
    "observacao": "Observação",
    "origem": "Origem",
    "paletes": "Paletes",
    "patrimonio": "Patrimônio/nome",
    "periodo": "Período",
    "placa": "Placa",
    "planejado": "Planejado",
    "prioridade": "Prioridade",
    "problema": "Problema",
    "produto": "Produto",
    "qtd_conferida": "Qtd. conferida",
    "qtd_esperada": "Qtd. esperada",
    "qtd_paletes": "Qtd. paletes",
    "pode_remontar": "Dá para remontar",
    "qtd_remontavel": "Qtd. remontável",
    "loja_plataforma": "Loja plataforma",
    "empilhadeira_indisponivel": "Empilhadeira indisponivel",
    "plataforma_operacional": "Plataforma operacional",
    "tacografo_frequencia": "Tacografo",
    "status_operacional": "Status operacional",
    "local_atual": "Local atual",
    "orientacao_frota": "Orientacao da frota",
    "carga_retorno": "Esta trazendo algo no caminhao",
    "carga_retorno_descricao": "O que esta trazendo",
    "exige_plataforma": "Exige plataforma",
    "motivo_plataforma": "Motivo plataforma",
    "carregado_em": "Carregado em",
    "quadro_atual": "Quadro atual",
    "quantidade": "Quantidade",
    "responsavel": "Responsável",
    "saida": "Saída",
    "saldo_fisico": "Saldo físico",
    "saldo_sistema": "Saldo sistema",
    "setor": "Setor",
    "status": "Status",
    "frequencia": "Frequencia",
    "status_intercalacao": "Status da passagem por outro CD",
    "intercala_cd": "Vai passar por outro CD",
    "intercalacao_concluida": "Passagem concluída",
    "observacao_intercalacao": "Observação da passagem",
    "cd_lacre": "CD do lacre",
    "descricao_ocorrencia": "Descrição da ocorrência",
    "lacre": "Lacre",
    "loja_destino": "Loja destino",
    "motivo": "Motivo",
    "tratado_por": "Tratado por",
    "tarefa": "Tarefa",
    "tipo": "Tipo",
    "tipo_chamado": "Tipo de chamado",
    "tipo_caminhao": "Tipo do caminhão",
    "tipo_unitizador": "Tipo de unitizador",
    "turno": "Turno",
    "quadro_padrao": "Quadro padrão",
    "unidade": "Unidade",
    "unidades": "Unidades",
    "valor": "Valor",
    "valor_estimado": "Valor estimado",
    "validade": "Validade",
    "cargas": "Cargas",
    "conferente": "Conferente",
    "crossdocking_produzido": "Crossdocking produzido",
    "horas_picking": "Horas picking",
    "horas_pulmao": "Horas pulmão",
    "minutos_trabalhados": "Minutos trabalhados",
    "onda_gerada": "Onda gerada",
    "ordem": "Ordem",
    "pendencia_itens": "Pendência itens",
    "pendencia_volume": "Pendência volume",
    "picking": "Picking",
    "produzido_itens": "Produzido itens",
    "produzido_volume": "Produzido volume",
    "pulmao": "Pulmão",
    "qtd_itens": "Qtd. itens",
    "qtd_volume": "Qtd. volume",
    "recursos_picking": "Recursos picking",
    "recursos_pulmao": "Recursos pulmão",
    "sem_agendamento": "Sem agendamento",
    "separacao_picking_produzido": "Separação picking produzida",
    "separacao_pulmao_produzido": "Separação pulmão produzida",
    "tipo_painel": "Tipo de painel",
    "total_a_produzir": "Total a produzir",
    "palete_pbr": "PBR",
    "palete_chep": "CHEP",
    "palete_chapatex": "Chapatex",
    "palete_descartavel": "Descartáveis",
    "vasilhame_coca": "Coca retornável",
    "vasilhame_cerveja": "Cerveja/engradado",
    "palete_cheio": "Paletes cheios",
    "palete_vazio": "Paletes vazios",
    "local_tipo": "Tipo de local",
    "local_codigo": "Codigo",
    "local_nome": "Local",
    "tipo_palete": "Tipo de pallet",
    "quebrados": "Quebrados",
    "reservados": "Reservados",
    "disponivel": "Disponivel",
}
